### ISSUE TITLE
Broken backspace

### ISSUE THREAD

**Issue by zetok** [JFreegman/toxic#163]
After https://github.com/Tox/toxic/commit/09badaa9ee6b4d2ff8a5b136dc1b1481739ae264 toxic no longer supports backspace.

**Comment by CLI-User** [comment]
Not sure if I am reading this right, or if my issue is intended, but I seem to not be able to delete text with backspace either. I have to use the delete key after going to the beginning of the text I want to delete. It has been this way for a while, I just thought it was normal, until searching about it to make a suggestion to add the ability to remove text via the backspace key.

**Comment by JFreegman** [comment]
> Not sure if I am reading this right, or if my issue is intended, but I seem to not be able to delete text with backspace either. I have to use the delete key after going to the beginning of the text I want to delete. It has been this way for a while, I just thought it was normal, until searching about it to make a suggestion to add the ability to remove text via the backspace key.

Can you give me more information about the environment you're running toxic on? If you know the code emitted by your backspace key that would also help.

**Comment by CLI-User** [comment]
> > Not sure if I am reading this right, or if my issue is intended, but I seem to not be able to delete text with backspace either. I have to use the delete key after going to the beginning of the text I want to delete. It has been this way for a while, I just thought it was normal, until searching about it to make a suggestion to add the ability to remove text via the backspace key.
> 
> Can you give me more information about the environment you're running toxic on? If you know the code emitted by your backspace key that would also help.

Not sure if this is of any help?
`^H        8 0010 0x08`

The OS is Ubuntu 22.04

I did not compile toxic I just ran the release version.
Toxic version 0.12.0                                                                                                                             
Toxcore version 0.2.18

**Comment by JFreegman** [comment]
First you should update to 0.13.0 so we can determine if the bug still exists in the latest release. 

Have you tried a different terminal emulator? Are you using it under something like Screen, Tmux, or through SSH? It sounds like your terminfo is misconfigured. It would be worth trying to compile from source to see if that solves the issue.

**Comment by CLI-User** [comment]
> First you should update to 0.13.0 so we can determine if the bug still exists in the latest release.

I updated to this version and it still does not work. 

> Have you tried a different terminal emulator? Are you using it under something like Screen, Tmux, or through SSH? It sounds like your terminfo is misconfigured. It would be worth trying to compile from source to see if that solves the issue.

However when you said this, I thought to check my current terminal emulator and I see there is an option to change the emulation behavior, I switched from default to Linux, and it now works haha.

This changes the showkey to 
`^?      127 0177 0x7f`

0x7f being correct in the code :)

I will have to get around to building toxic as I want sound, thanks haha.
