### ISSUE TITLE
PGP/GPG point-to-point encryption support

### ISSUE THREAD

**Issue by XVilka** [JFreegman/toxic#217]
To be able to use GPG easily for the messages

**Comment by XVilka** [comment]
Is it possible to reopen this one? Still very important I think.

**Comment by GrayHatter** [comment]
what benefit would you gain by this?

**Comment by XVilka** [comment]
Additional layer of security.

**Comment by JFreegman** [comment]
Can you go into more details about how this might increase security? If you can make a good argument that doesn't amount to "more encryption == better" I might consider it.

Edit: Also, how would you envision this PGP support?
