### ISSUE TITLE
Multi-line input form

### ISSUE THREAD

**Issue by haasn** [JFreegman/toxic#224]
I would like an option to make the input box at the bottom of the window grow to multiple lines in height.

To clarify:
- When typing a message longer than the width of the input box, it should cleanly wrap into the next line instead of scrolling horizontally, expanding the dialog's height in the process.
- When pasting something into the terminal, line breaks should not send partial messages, but the whole thing should show up in the input as-is.
- Hitting shift+enter or control+enter or some other combination should advance into the next line, rather than sending the message.

**Comment by blendi-93** [comment]
+1

**Comment by MrSorcus** [comment]
+1
Any progress?

**Comment by metala** [comment]
How do we resolve person/user impersonation in this case? e.g. "\n<impersonated_user>text"

**Comment by JFreegman** [comment]
@MrSorcus I have no plans on changing the input box. The UI is too hacky and I don't have the time.

@metala The formatting would look different
