### ISSUE TITLE
[Regression] Hangs when sending larger amount of text from paste

### ISSUE THREAD

**Issue by zetok** [JFreegman/toxic#266]
4e9f125e956a5efd566dbf46c2393468d577b570
CPU usage at 100%..

I used same test sample as before to test, when testing Toxic hanged at 2 different positions in text sample.

**Comment by JacobHenner** [comment]
Just replicated the issue, TOXIC 0.6.1_r1557. It pasted many lines successfully, and then finally hung. x64 Arch Linux.
