### ISSUE TITLE
Abnormal high CPU usage

### ISSUE THREAD

**Issue by zetok** [JFreegman/toxic#275]
![pls fix](https://cloud.githubusercontent.com/assets/3148759/4767281/f304efa8-5b5b-11e4-845d-4543a55c6a77.png)

No idea what have caused it.

**Comment by Bizzaro** [comment]
Looks like some kind of resource leak... 
![screen shot 2015-01-10 at 6 42 49 am](https://cloud.githubusercontent.com/assets/10475262/5691444/759269ee-9894-11e4-915f-c2e089880fdf.png)

**Comment by JFreegman** [comment]
In order to fix this I would need to know which function is using all those resources. Were you doing anything in particular that may have triggered it?

**Comment by stal888** [comment]
@Bizzaro that is caused by killing the terminal toxic is running in.
