### ISSUE TITLE
Installation failed on ubuntu 12.04, package missing

### ISSUE THREAD

**Issue by profugo79** [JFreegman/toxic#279]
Hi,

Package libconfig9 is missing.
After adding Tox deb repository as suggested, I get this message from terminal (formerly ~~in French sorry~~) :

me@mypc:~$ sudo apt-get install toxic
Reading package lists ... done
Constructing the dependency tree

Reading state information ... done
Some packages could not be installed. This can mean
you have requested an impossible situation or if you use
the unstable distribution that some required packages have not yet
created or are not out of Incoming.
The following information should help you to resolve the situation:

The following packages have unmet dependencies:
toxic: Depends: libconfig9 but it is not installable
E: Unable to correct problems, defective packages mode "keep as is".

Anyone can help pls?

++

**Comment by louipc** [comment]
Hello when you run a command for debug purposes please run it like this:
LANG=C command

That will fix the translation messages.
