### ISSUE TITLE
long timestamp_format causes strange characters on screen

### ISSUE THREAD

**Issue by louipc** [JFreegman/toxic#304]
The issue, if I set some long format like
`timestamp_format: "%a %Y-%m-%d [%H:%M:%S] %s"`

in misc_tools.c:90

> ```
> strftime(buf, bufsize, t, get_time());
> ```

I would have expected strftime to trunc the output string appropriately, but that's not the case.
from strftime man page:

> If the length of the result string (including the terminating null byte)
> would exceed max bytes, then strftime() returns 0, and the contents of the
> array are undefined.

So instead of truncating the string to bufsize, it will create some strange
array and print strange artifacts to the screen. It doesn't seem to affect
printing to the log.

I added a couple lines to try to examine what was happening

```
src/misc_tools.c
@@ -90,7 +90,8 @@ void get_time_str(char *buf, int bufsize)
     const char *t = user_settings->timestamp_format;
-    strftime(buf, bufsize, t, get_time());
+    size_t test = strftime(buf, bufsize, t, get_time());
+fprintf(stderr, "%d %zu %zu %s\n", bufsize, strlen(buf), test, buf);
```

On screen I can see something like this:
`Tue 2015-02-24 [21:05:47] ~[oѱ0 >> francobot has come online`

stderr:
`32 41 0 Tue 2015-02-24 [21:05:47] �oѱ0�francobot`

log seems to be unaffected (which is strange to me):
`Tue 2015-02-24 [21:05:47] 1424829947 * francobot has come online`

I'll come up with a solution, but any recommendations are appreciated.

**Comment by JFreegman** [comment]
Better late than never https://github.com/JFreegman/toxic/commit/a69fad15c1ee5737872f2b9649dc3f366914f9df
