### ISSUE TITLE
Screen flickers with tmux

### ISSUE THREAD

**Issue by sevcsik** [JFreegman/toxic#305]
I'm using toxic v0.5.2 on a headless server, via tmux. I could reproduce it using the debian package and the latest toxic-git PKGBUILD from AUR.

The issue is that under tmux, the cursors jumps back and forth about 3 times in a second, and when I open the help dialog, or any other overlay, the whole dialig flickers. Also, the CPU usage is constantly between 30-60% (only when the windows is active).

When I start toxic without tmux, there's no flickering and the CPU is also normal (1-2%).

Using tmux, my TERM is screen-256color, otherwise it's xterm-256color, but I tried numerous values without any results.

**Comment by louipc** [comment]
May be related to https://github.com/Tox/toxic/issues/194

**Comment by HalosGhost** [comment]
:+1: confirmed on Archlinux with latest tox{ic}-git packages from the AUR.

**Comment by saper** [comment]
Same here on FreeBSD/amd64, under tmux

**Comment by pickfire** [comment]
Yeah, me too, screen flickers in `st`.

**Comment by mrhmouse** [comment]
I get the same bug in MinTTY on Windows, running over SSH.

**Comment by Zer0-One** [comment]
same issue with st/screen/ssh

**Comment by NicoHood** [comment]
for me it applies to tty1 on elementary os.

**Comment by metala** [comment]
Is it still reproducible with the latest master?

**Comment by HalosGhost** [comment]
Yes. it is.

**Comment by HalosGhost** [comment]
Looks like one of the last few commits fixed it for me!

**Comment by mrkiko** [comment]
Seems fixed to me too, or at least cursor seem to flicker very infrequently, if at all.
