### ISSUE TITLE
Cannot work on Rasperberry Pi

### ISSUE THREAD

**Issue by LER0ever** [JFreegman/toxic#317]
All the libraries needed is installed and it says "Illegal instruction" at the first run.
(I downloaded the toxic armv6 and required libraries from tox jenkins)

**Comment by dubslow** [comment]
@stqism

**Comment by urras** [comment]
Actually, I think this ones mine. Gimmie a few hours, and if I don't respond within a day, feel free to poke me here or on IRC.

**Comment by urras** [comment]
@LER0ever So, the binaries on Jenkins are really old, and I've been having trouble compiling Toxic for ARMv6 lately. I'll try to fix it this week, but for now I recommend that you compile from source:)

**Comment by LER0ever** [comment]
OK, i'll try to compile from source to see if the problem can be solved. Thanks!

**Comment by pickfire** [comment]
It works using the raspberry pi 2 by compiling it manually.
