### ISSUE TITLE
/myid doesn't show qrcode

### ISSUE THREAD

**Issue by swiftgeek** [JFreegman/toxic#326]
/myid doesn't show qrcode, or just command for showing it is missed from /help messages

Example apps showing qr codes in console
(lib)qrencode could be used for that https://fukuchi.org/works/qrencode/
or even something from systemd's journald ~ https://github.com/systemd/systemd/blob/master/src/journal/journal-qrcode.c

**Comment by JFreegman** [comment]
There doesn't seem to be much demand for this.

**Comment by subliun** [comment]
Antox users would like it. Perhaps as a separate command though.

**Comment by JFreegman** [comment]
Yeah let's put this on the TODO list

**Comment by JFreegman** [comment]
Done: https://github.com/JFreegman/toxic/commit/39c4b7ecdd5ecfac488dbc85e3762e4a8aabf5e4
