### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#329]
This happens on exit via /quit (with -b on):

```
$ toxic -4 -b
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  25 (X_SendEvent)
  Value in failed request:  0x0
  Serial number of failed request:  27
  Current serial number in output stream:  27
```

tested with https://github.com/Tox/toxic/commit/0bc610e18dc22112d57c744db13c66e385cccf15

EDIT: a different one looks the same(but 27 is 37):

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  25 (X_SendEvent)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  37
```

**Comment by JFreegman** [comment]
You can ignore these errors, I've looked into them and they don't seem harmful. Maybe @mannol knows what they mean and how to make them go away?

**Comment by emanueLczirai** [comment]
I agree seems harmless.
One thing's for sure, execution doesn't go past this `while` https://github.com/Tox/toxic/blob/e55e5f3f7e939915a93077f016a8df815910feb9/src/xtra.c#L359
Something else exits with exitcode 1 ie. exit(1); or exit(EXIT_FAILURE);  (even without -b)

**Comment by emanueLczirai** [comment]
that `Major opcode of failed request:  25` made me think it's the resize event, but tbh I've no idea.
`#define ResizeRequest   25                                                      `
in `/usr/include/X11/X.h`
