### ISSUE TITLE
SSH alerts

### ISSUE THREAD

**Issue by P8ntBal1551** [JFreegman/toxic#336]
Is it possible to play the alerts through an ssh connection?

**Comment by JFreegman** [comment]
You should be able to get a terminal bell through SSH, though not the actual sounds. Play around with your terminal settings and make sure you have all the sound related dependencies.

**Comment by P8ntBal1551** [comment]
thanks for you answer

looking at the settings, i believe i may have found the problem

im using putty, the default is use system default alert, and i have no system sounds

sorry and thank you again

**Comment by P8ntBal1551** [comment]
well, after an hour of testing, it wasn't that.

could it be a problem with me having it in a screen session inside the ssh?

**Comment by JFreegman** [comment]
It could be. I use tmux and it works for me. Although a friend of mine has had the same problem with screen. You might want to try without screen or with tmux, just to see if that's the issue. It could also be an issue with putty, which I'm not familiar at all with.

**Comment by P8ntBal1551** [comment]
Nope, just tried it, didn't work.

is there a setting in the config file to do with it?

**Comment by P8ntBal1551** [comment]
BTW, it's not putty, if i backspace on a blank line, the bell is triggered

and it's not screen because it doesn't work when screen is off

in ~/.config/tox/toxic.conf (that is the right place, right?) there is "alerts=true;" which should be the option, right?

**Comment by JFreegman** [comment]
That's right. Are you sure you installed freealut? (libalut-dev for debian)

**Comment by P8ntBal1551** [comment]
i went back and installed all the dependencies, turns out that one and the notification ones weren't installed

killed toxic, killed screen, opened toxic out of a screen and still nothing

If you can think of anything else sweet, if not don't worry about it, i've probably taken up too much of your time already

thanks

**Comment by JacobHenner** [comment]
@P8ntBal1551 Can you provide the name and versions of the terminal you are using, the OS, any screen/tmux/etc, the ssh client, etc? (On both your local machine and the remote)

**Comment by P8ntBal1551** [comment]
@JacobHenner im running it from a debian server - so no terminal emulator, just the terminal, i am using screen to save my session. The ssh clients are mint's openssh client running in a tilda session, and on windows I use putty and puttytray.

**Comment by ghost** [comment]
It seems nobody ever replied back to this topic, but as of today I'm having the same questions and problems. Is there a way to enforce the terminal BEL char on every message I receive?

Instead of just the "---" I want to add something like 0x07 or "\a" on messages (prefeably only the ones received).

PuTTY is used here as well, as it is the only SSH client I'm allowed to use at work.

**Comment by GrayHatter** [comment]
1) try `echo \\a` if your ssh client makes noise with that, it's not your client

2) try toxic without any session preserving term

If it still doesn't make noise, and you confirmed that your toxic settings are correct. Then it'd be toxic's fault.

**Comment by ghost** [comment]
@GrayHatter Thanks for your reply,
echo -e "\07" and echo -e "\a" work nicely, also does the backspace key

If I run toxic with or without tmux I do not get alerts. Editing toxic.conf message formatting **---** with a hex editor and forcing the 0x07 ASCII representation of terminal bell did yield at least the **-_^G_-** representation of it in the output, but no alerts were received.

After this I ran out of ideas what else I could try. The wish to have an audible notification isn't new for me, I even tried to figure out if I could somehow have the sound tunnel over SSH, but that is even harder to pull of for me.  Flashing or beeping PuTTY would make me very happy already.

**Comment by GrayHatter** [comment]
You'd need an external lib to do that... (IIRC)

I'm going to guess ncurses is clobbering the \a somehow

**Comment by ghost** [comment]
@GrayHatter 
It is the binary from here https://wiki.tox.chat/binaries (no X11)  if that matters anything. The device is a raspberry pi 2 with Debian server.

If it is not planned on being implemented I can understand this, but it is a feature I personally, and probably those who asked about it before me would very much enjoy.

This should be tagged as bug unless the issue is because of my own setup and shortcomings.

**Comment by GrayHatter** [comment]
If you're willing to take the time to set it up... the last time I looked into streaming audio over ssh with putty, (which I gave up on before I got it working), was to use pulse_audio and net_jack to stream over a port forward created by putty.

**Comment by ghost** [comment]
Don't know how many hours I tried today and some weeks ago, but I give up. Guess I unsubscribe from this topic, if things change I will notice during my updates. Don't think there are enough PuTTY users so far to make this a priority. Thanks for your time though and trying to be helpful with such patience :)

**Comment by ghost** [comment]
I fixed it!

**/home/$username/.tmux.conf**
`set -g default-terminal "putty-256color"`
`set-option -g bell-on-alert on`

(The 256 colours are just for being fancy with other stuff, but useful.)
Got a nice BELL sound now with PuTTY. Maybe add to documentation or close, at least this will help others like P8ntBal1551.

**Comment by JFreegman** [comment]
So it was a tmux problem? I don't really think this belongs anywhere in the toxic repo since it's just too cumbersome for me to try to officially support every third party application that comes along. Maybe someone could start a 'third party support' section in the wiki or something.

**Comment by GrayHatter** [comment]
You could enable global edits on the github wiki here

Then when someone works it out, they can post it there?
