### ISSUE TITLE
Error code -2, crash on startup

### ISSUE THREAD

**Issue by Derpford** [JFreegman/toxic#339]
When I try to launch toxic, I get this message:
>Toxic session aborted with error code -2 (failed in load_toxic)

Nothing else prints to the console, and the program does not launch. Running with -b does not show any additional output.

**Comment by JFreegman** [comment]
That's a file operation error. Is it possible that you don't have write permissions for the process?

**Comment by Derpford** [comment]
It's not likely, but I'll check.

**Comment by Derpford** [comment]
Question: What files should toxic be accessing? I've reset my toxic.conf to the defaults, and made it readable for all groups.

**Comment by JFreegman** [comment]
Assuming you're not using the -f option, the file in question is ~/.config/tox/data. You might also want to try running with -f to see if that changes anything

**Comment by Derpford** [comment]
Running with -f lets me create a new file, and toxic launches with this new file without any errors popping up.
It re-launches with this file without incident.
Launching without -f, or using -f to point at my original data file, causes an error.

**Comment by JFreegman** [comment]
Just to be sure delete (or rename) your original data file and see if it magically resolves when it creates a new one (without -f). If it doesn't, we can rule out file corruption. It sounds like a system configuration issue to me.

**Comment by Derpford** [comment]
Creating a new file appears to be working. But I'm gonna have to redo all
my contacts, I guess...

**Comment by JFreegman** [comment]
Any extra info you can give me on what might have caused it? Is it an old file? Did you use it with other clients?

**Comment by mytch444** [comment]
I've been getting this lately also, it happens when the computer crashes and toxic doesn't get to save the data properly I think.

**Comment by JFreegman** [comment]
@mytch444 Quite possible. That should be fixed now.
