### ISSUE TITLE
Problems linking to toxcore

### ISSUE THREAD

**Issue by teh-jazzman** [JFreegman/toxic#347]
I am having great difficulties linking toxic to toxcore because there are always missing symbols. I got it working before but only with very specific commits on both sides. Is there some "official" toxcore version toxic needs to link against or am I missing something else here?

**Comment by louipc** [comment]
On Fri 24 Jul 2015 11:01 -0700, Stefan Mühlinghaus wrote:
> I am having great difficulties linking toxic to toxcore because there are
> always missing symbols. I got it working before but only with very specific
> commits on both sides. Is there some "official" toxcore version toxic needs
> to link against or am I missing something else here?

You're not alone. Both codebases and development workflows are both works in
progress, so you'll have to track at which states both work together yourself.
You might find useful info by asking in the tox irc channels and mailing lists.
