### ISSUE TITLE
"No pending friend requests." while"Friend request has already been sent."

### ISSUE THREAD

**Issue by saper** [JFreegman/toxic#348]
I have a `tox_save.tox` file taken from µTox 0.3.2 on Windows. While on Windows I sent one friend request (no answer yet).

Now trying toxic on FreeBSD/amd64: 0.6.0_r409e4dd (409e4dd) .

Started with `toxic -f path/to/my/tox_save.toc`.

`/myid` identifier matches what I've got on µTox.

I try this sequence of commandss:

```
Using '/home/saper/.config/tox/tox_save.tox' data file                                
X failed to initialize                                                                
Avatar is not set.                                                                    
$ /requests                                                                           
No pending friend requests.                                                           
$ /add 3FA2E52.... 
Friend request has already been sent.                                                 
$ /requests                                                                           
No pending friend requests.                                                           
````

This `3FA2E52...` is the same ID that was added on Windows.

The messages are contradicting themselves.

I can repeat `/add` and `/requests` and the output is always as above.

**Comment by JFreegman** [comment]
/requests is for listing inbound requests, not outbound.

**Comment by saper** [comment]
So you don't think it's a UI problem...

**Comment by JFreegman** [comment]
What's the issue exactly?

**Comment by saper** [comment]
I find this message confusing... Is it possible to say how many outgoing requests were sent as well? Or, if not possible, just say "No incoming friend requests pending." ?

**Comment by JFreegman** [comment]
Your outgoing friend requests are shown in the contact list as Anonymous.
