### ISSUE TITLE
Segfault on Void Linux

### ISSUE THREAD

**Issue by Derpford** [JFreegman/toxic#353]
After making a new user file, Toxic segfaults with no other output.

Maybe it's not able to create the file properly?

**Comment by JFreegman** [comment]
Could you give me your exact steps and provide a stack trace using gdb?

**Comment by Derpford** [comment]
Step 1: Run "toxic" in my preferred terminal, Terminology.
Step 2: Decide whether or not to encrypt my user file.
Step 2a: If encrypting the user file, type password.
Step 3: Wonder why there's a segfault.

**Comment by JFreegman** [comment]
You said after making a new user file. What do you mean by this?

**Comment by Derpford** [comment]
Tox tries to make a new user file.
Then it crashes. The only input I get in this process is deciding whether
or not to encrypt it.

**Comment by JFreegman** [comment]
Does it work if you run toxic as superuser?

**Comment by Derpford** [comment]
Ran through sudo: Nope. No output, either--not even the segfault.
Using su: I get the segmentation fault message, but still no results.
Using su, no encryption: Nope, segfault.

**Comment by JFreegman** [comment]
If you're building from source can you tell me which commit you're on for both toxic and toxcore? also try to `make clean && make && make install`. If not, what binary version?

**Comment by quaeched** [comment]
Happened to me as well on musl. glibc working fine, though.
