### ISSUE TITLE
Warning when I tried to port my config - and locked out of all commands

### ISSUE THREAD

**Issue by kozross** [JFreegman/toxic#356]
I basically tried to get the exact same config on another machine of mine by just copying out the entire `.config/tox` directory. Now, once a contact came online, I saw this:

```
WARNING: Failed to save to data file
WARNING: Failed to save to data file
WARNING: Failed to save to data file
WARNING: Failed to save to data file
WARNING: Failed to save to data file
WARNING: Failed to save to data file
```

I'm not sure if this is intentional and how I can avoid it, but I figured I'd post it here anyway.

Edit: It also seems to lock me out of _any_ commands on top of that. Like, any command registers invalid - even `\help`!

**Comment by JFreegman** [comment]
@kozross commands start with a forward slash `/`, not a backwards slash '\'.

That fail to save warning probably means the toxic process doesn't have write permissions for the directory you copied the data to.
