### ISSUE TITLE
"Glitchy" terminal cursor in st

### ISSUE THREAD

**Issue by ploz** [JFreegman/toxic#359]
While using the st terminal client, the cursor bar ( █ ) likes to rapidly flash on the screen from where the user can type to right beside "[contacts]" (or whatever is at the end of that section). Everything seems to still work correctly however it is very distracting and annoying while trying to use Toxic.

**Comment by JFreegman** [comment]
This remains an unsolved mystery. Try using a different terminal emulator.

**Comment by ploz** [comment]
I think it is more of a problem with st rather than toxic. While running a few other programs (like mpv for example) it likes to display flashing text as well.
