### ISSUE TITLE
Compiling video_device.c on FreeBSD

### ISSUE THREAD

**Issue by thierry-FreeBSD** [JFreegman/toxic#364]
src/video_device.c contains many #ifdef **linux** and other systems are considered as OSX, which fails.
When the port multimedia/v4l_compat has been installed, these "#ifdef **linux**" can be extended to support FreeBSD. Please see the attached patch.
[src_video__device.c.diff.txt](https://github.com/JFreegman/toxic/files/32714/src_video__device.c.diff.txt)

**Comment by JFreegman** [comment]
Fixed, thank you again.
