### ISSUE TITLE
Using proxy with authentication

### ISSUE THREAD

**Issue by sbmueller** [JFreegman/toxic#371]
In addition to #355: What if my proxy needs authentication? Where can I enter my login data?

**Comment by ovalseven8** [comment]
Toxcore issue: https://github.com/irungentoo/toxcore/issues/1268

**Comment by sbmueller** [comment]
Alright thanks for the info

**Comment by JFreegman** [comment]
Hopefully someone can remind me of this if/when toxcore gets support for it.
