### ISSUE TITLE
Toxic fails to initialize if ~/.config directory doesn't exist

### ISSUE THREAD

**Issue by wedge-jarrad** [JFreegman/toxic#372]
Installed Toxic on FreeBSD 9.2 with `pkg install toxic`. No .config directory existed in my home directory and Toxic failed to create it. Same problem occurs on Ubuntu 14.04 (installed from source) if the .config directory is not present.

```
$ toxic
Toxic session aborted with error code -2 (failed in init_default_data_files())
```

Easy workaround is to first manually create the .config directory:

```
$ mkdir ~/.config
```

Toxic then initailizes as expected, creating the tox/ subdirectory and so on.

**Comment by Lesik** [comment]
I just wanted to say that this "bug" occured for me, as well. It has been fixed, but there has been no release yet. I'm not saying you should rush it, just wanted to add to the protocol that there were multiple people affected by this.

**Comment by JFreegman** [comment]
@Lesik what do you mean there's no release? Are you talking about a new toxic version?

**Comment by Lesik** [comment]
I mean a git release: https://github.com/JFreegman/toxic/releases

**Comment by JFreegman** [comment]
@Lesik You should be using the latest commit rather than the latest release. Releases are currently arbitrary and usually only come after major changes.

**Comment by Lesik** [comment]
My distro packages only releases - which I find a good idea. Usually, when using git, the master branch can contain experimental code that was pushed for collaborating purposes and not for actual usage. Whereas releases indicate a commit at which the code was (more or less) fully working and ready for use. At least in my experience this is what is usually done.

Thanks for the heads up though.
