### ISSUE TITLE
Manpage not always included

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#376]
I recently install Toxic (from the official Tox PPA), and I wanted to look at its manpage, however when typing:

```
man toxic
```

I just get this:

```
No manual entry for toxic
See 'man 7 undocumented' for help when manual pages are not available.
```

Though I have spoken to somebody else who has installed Toxic the exact same way and yet when they try this, they actually get the Toxic manpage so this is very strange.

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
toxic:
  Installed: 0.7.0-166
  Candidate: 0.7.0-166
  Version table:
 *** 0.7.0-166 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by JFreegman** [comment]
Should be fixed now with the debian repo
