### ISSUE TITLE
How to export your profile?

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#377]
I recently installed Toxic, but after looking in the `/help` section, and getting someone else to look in the manpage for me (as I cannot access it), I still can't figure out how to export my profile in order to import it into another Tox client. And [here](https://wiki.tox.chat/clients) it does say that it can be done. So how can this be done?

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
toxic:
  Installed: 0.7.0-166
  Candidate: 0.7.0-166
  Version table:
 *** 0.7.0-166 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by alexeysvrv** [comment]
@SeventhSonOfASeventhSon 
`toxic -f /your/profile.tox`

**Comment by ghost** [comment]
@alexeysvrv, Thanks!
