### ISSUE TITLE
Distorted sound from other clients

### ISSUE THREAD

**Issue by AshSlave** [JFreegman/toxic#378]
Audio calls between two toxic clients work fine, but sound coming from other clients (tested with utox and qtox) is distorted to the point of being incomprehensible. Other clients receive audio from toxic without problems.

**Comment by Zer0-One** [comment]
@AshSlave have you tried disabling audio filtering on uTox and qTox? How old are the builds of each of your clients?

**Comment by AshSlave** [comment]
@Zer0-One On uTox yes, tried with and without audio filtering - something changes, but it doesn't make audio any clearer. I tested builds of Toxic and qTox from Arch Linux's official repository, Toxic, qTox and uTox from tox-overlay in Gentoo and also tried with unknown version of qTox of some Windows user. Result is always the same, no matter how I combine them. It started few months ago, when I updated Toxic, but I didn't care too much and just used uTox instead.

**Comment by ElLamparto** [comment]
I confirm. The same happens to video, by the way.

Outgoing toxic audio and video are processed correctly by qtox, But receiving qtox audio and video by toxic is next to impossible.

Not long ago, there were no problems with audio. toxic, utox and qtox worked fine together.

By the way:                         **\* BIG THANKS FOR VIDEO ***

**Comment by JFreegman** [comment]
Nothing has changed in toxic's A/V code recently. It must be related to the core. @mannol any ideas?

**Comment by alexbakker** [comment]
It's possible that uTox and qTox allow toxav to decrease the bitrate to the point where sound becomes distorted. Are you seeing any entries related to bitrate changes in the logs?

**Comment by AshSlave** [comment]
@Impyy I haven't found anything related in .config/tox. There is this terminal output from qTox in the middle of audio call with Toxic:
`[12:33:24.565] src/audio/audio.cpp:506 : Debug: Audio output not closed -> there are pending subscriptions.`
But I don't know if it's related.

**Comment by alexeysvrv** [comment]
I agree. Very poor sound quality. This companion is strongly accelerated, and poor quality. He hears me okay. I use Toxic, he use qTox

**Comment by sylware** [comment]
I do confirm that rx audio call is garbled in (very recent) toxic from (very recent) µtox (my girlfriend receives audio fine in µtox)
(git libsodium/toxcore/toxic on up-to-date debian jessie x86)

**Comment by JFreegman** [comment]
I just pushed a fix for this https://github.com/JFreegman/toxic/commit/4e0e322e32b0d7b5d1692f72876ac7f9ae2e610a

Let me know if it worked please (you might have to wait 24h if you're using the packaged version).

**Comment by sylware** [comment]
On Mon, Apr 04, 2016 at 09:51:14PM -0700, JFreegman wrote:

> I just pushed a fix for this https://github.com/JFreegman/toxic/commit/4e0e322e32b0d7b5d1692f72876ac7f9ae2e610a
> 
> Let me know if it worked please.

Audio is fixed, nice! But I tested video call feature on my logitech C615:
green picture with garbled top.  (µtox is fine).

## 

Sylvain

**Comment by ElLamparto** [comment]
I have the same problem with video as @sylware. Even if toxic is on both ends of the connection.
