### ISSUE TITLE
Don't auto-cancel actions

### ISSUE THREAD

**Issue by TheLastProject** [JFreegman/toxic#381]
Toxic seems to automatically cancel file transfers and voice calls if they are not answered quickly. For example, qTox doesn't automatically cancel transfer file transfers and it at very least gives me enough time to actually plug my headset in, lower my music volume and change my alsamixer settings.

It would be nice to be able to raise this timeout by default and disable it for file transfers (as it makes no real sense to auto-expire those).

**Comment by JFreegman** [comment]
Toxic doesn't have a voice call timeout. I think it used to, but as of the latest build it does not. If it's not ringing forever, it has to do with the other client. As for file transfer timeouts, I can't remember my reason for adding them, so that's been removed.
