### ISSUE TITLE
Aliases for the contacts

### ISSUE THREAD

**Issue by ovalseven8** [JFreegman/toxic#382]
Hello,

one of the last features that are missing is the ability to set aliases for the contacts.
It's an important issue because then you're independent of nickname changes from your contacts and you can decide for yourself about how somebody should be called in your contact list.

**Comment by JFreegman** [comment]
I believe that this is a core feature, as implementing it in the client would require a lot of unnecessary duplicate work. Until toxcore gets alias support, toxic will have to do without.

**Comment by JFreegman** [comment]
Done https://github.com/JFreegman/toxic/commit/6dc22b519c31512c970dcf2afb91976bf5e5a73e
Will be in the next release.
