### ISSUE TITLE
Save QR code in PNG file format

### ISSUE THREAD

**Issue by ovalseven8** [JFreegman/toxic#383]
Hello,

at the moment Toxic saves the QR code with a .QRcode file extension, what's nothing else than a simple text file, no?

I would prefer a PNG file because it's much more convenient to work with.
Perhaps it's possible to change the file format or to add a command like **/myqr png** or something like that.
As far as I know, libqrencode supports PNG output as well.

Nonetheless, the .QRcode file opened with an editor did its job. :wink:

**Comment by JFreegman** [comment]
I don't see why this would be necessary. A text file does everything a PNG file does.

**Comment by snow4life** [comment]
Except that it cannot be pasted in places that mess up the text formatting, like a facebook comment...
I love the text QR, but it would be useful to have the option.

**Comment by JFreegman** [comment]
Just take a screenshot and scale as needed. You only need to do it once. http://i.imgur.com/lQP9PNW.png

Yes it would be slightly more convenient to have a PNG option, but it's also more work, adds one more confusing option, and is entirely unnecessary. Toxic is ostensibly a minimalist client. That said, if someone makes a pull request I'll accept it.

**Comment by Ansa89** [comment]
Please note that JFreegman/toxic#411 adds `libpng` as dependency.
