### ISSUE TITLE
Reconnect on network change

### ISSUE THREAD

**Issue by i-am-user** [JFreegman/toxic#384]
Using Debian GNU/Linux Jessie on a laptop.  Running Toxic using byobu terminal
Toxic mostly fails to find all Online contacts. When I change from cable to WiFi or connect/disconnect VPN 
Now script monitors changes in "ip addr" then kills toxic process and relaunches it.
Maybe there's better way to handle this?

**Comment by JFreegman** [comment]
Toxic does everything it can to reconnect on connection loss. This seems like a toxcore issue.
