### ISSUE TITLE
Separate notifications

### ISSUE THREAD

**Issue by i-am-user** [JFreegman/toxic#386]
Is it possible to disable "has come online/offline" but keep "incoming message" notifications?
hate "has come online/offline" flood

**Comment by JFreegman** [comment]
This is a feature I'd been meaning to add for a while. On the latest commit you should be able to use the config setting `show_connection_msg=false`. 
See: https://github.com/JFreegman/toxic/blob/master/misc/toxic.conf.example

**Comment by i-am-user** [comment]
nice :)
