### ISSUE TITLE
ERROR: toxini file 'tox.ini' not found

### ISSUE THREAD

**Issue by bgm145** [JFreegman/toxic#388]
Dear Sir/Madam,

I followed the Debian/Ubuntu instructions on page **https://pkg.tox.chat/ *_but when running the code displayed here *_https://wiki.tox.chat/binaries#other_linux** the following problem occurred when trying to update my system:-

**W: Failed to fetch http://ppa.launchpad.net/ne0sight/chrome-gnome-shell/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ne0sight/chrome-gnome-shell/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.**

the output when I try to run the tox in the shell:-
**
bryce@ug-x250:~$ tox
ERROR: toxini file 'tox.ini' not found**

Therefore I'm unable to run the tox system on my Ubuntu Gnome computer.Can you advise me about the problem please? What do I need to do to resolve this and what actually went wrong in the first place?

Thank you,
Bryce.

**Comment by JFreegman** [comment]
This isn't the appropriate place for packaging issues. Try our mailing lists. https://lists.tox.chat/listinfo
