### ISSUE TITLE
Nameserver Lookup List not Found

### ISSUE THREAD

**Issue by arcfide** [JFreegman/toxic#389]
I grabbed the 64-bit binarry build of Toxic and I'm currently trying to figure out how to properly install it. Following standard procedure I through the contents into a directory called /opt/toxic on my Slackware distribution, got the right dependencies to get it running, and then began playing around with my existing tox configuration. 

Right now the main issue I have is trying to understand why the run_toxic.sh folder has TERMINFO and ALSOFT_LOGLEVEL set as well as the need to manually specify the DHTnodes and nameservers list. If I do not specify these manually from their location in the /opt/toxic/misc/ directory toxic does not seem to be able to find them. Where should I be putting these files so that they are automatically found and used? What is the purpose of the terminfo and alsoft environment variables?

**Comment by JFreegman** [comment]
There's nothing to install for the binary. You simply extract the contents, run the shell script (don't move anything), and everything should just work. If you have to manually specify those files then you're doing something wrong.

The terminfo stuff is for portability. ALSOFT_LOGLEVEL=0 disables logging for openAL.

**Comment by arcfide** [comment]
I am trying to install Toxic rather than keep the installation somewhere in my home directory. I want to be able to run `toxic` from the command line and have it work. The intent is not to have a roaming, self-contained installation but rather something installed into the standard UNIX file system such as /opt or /usr/local, without cluttering my home directory up.

**Comment by JFreegman** [comment]
In that case I'd suggest installing it from source. Ideally you would just install a package, but we don't have slackware packages yet.

**Comment by arcfide** [comment]
Okay, I see. I'll try to get a SlackBuild package written up based on the source.
