### ISSUE TITLE
How can I copy everything from one computer to another?

### ISSUE THREAD

**Issue by P8ntBal1551** [JFreegman/toxic#391]
I'm recreating my virtual machines to containers, and I would like to migrate my toxic user files over, including my tox ID. Are there files that I could just straight copy from one machine to another?

Thanks.

**Comment by JFreegman** [comment]
The only file you need is the .tox file in your configuration directory. See the manual for a list of all files that toxic uses.

**Comment by P8ntBal1551** [comment]
Ahh, I see my problem. I had an older version of toxic installed and it used a file in ~/.config/tox called data. Is there a way of converting that file to the .tox file?

Thanks.

**Comment by JFreegman** [comment]
It should automatically convert that file to toxic_profile.tox when you run an up-to-date version of toxic. If it doesn't for some reason, you can just rename it yourself. Make sure you back everything up first though.

**Comment by P8ntBal1551** [comment]
It didn't work the first time, but i tried again from a copy of it and it worked. Thanks for all your help, and keep up the amazing work :D.
