### ISSUE TITLE
Symbolic linking profile causes link target to be deleted

### ISSUE THREAD

**Issue by Lohikar** [JFreegman/toxic#392]
I tried to move my toxic profile out of `~/.config/tox` by symbolically linking (`ln -s`) `toxic_profile.tox` to a profile saved in a ecryptfs mounted folder.

When I started toxic, toxic deleted the file at the end of the symbolic link, and tried to create a new profile at `~/.config/tox/toxic_profile.tox`, replacing the symbolic link.

I'm using Toxic 0.7.0_r1687 from `toxic-git` in the Arch AUR.

**Comment by JFreegman** [comment]
I can't reproduce this, but just a guess, maybe it was a permission issue? You shouldn't need to use a symbolic link anyhow. Just move the .tox file to wherever you want it and run `toxic -f <profile_path>.` You might find it helpful to run toxic from a shell script so you don't have to retype all of your custom options whenever you run it.

**Comment by Lohikar** [comment]
I tried again, paying attention to the permissions this time.
Oddly enough, it just copied the file the symbolic link pointed to to `~/.config/tox/toxic_profile.tox`, overwriting the link.

Throughout the entire process, the file(s) all had the correct owners and were all `600`.

I was hoping to avoid `-f` in my toxic shell script, but I can live with it.

**Comment by mrkiko** [comment]
I am trying to do the same thing to move toxic profile out of flash memory to avoid excessive writes.
Toxic writes on the file periodically.
I used a script like this:

#!/bin/sh

PATH=/usr/bin

if [ -a $HOME/.config/tox  ] && [ -d $HOME/.config/tox ]; then
  mv $HOME/.config/tox /tmp/ && ln -s /tmp/tox $HOME/.config/tox
fi
/usr/bin/toxic $@
rm $HOME/.config/tox && mv /tmp/tox $HOME/.config/tox

Consider this a quick and dirty solution: and yes, on multi-user system this is not good either.
