### ISSUE TITLE
video call "green" screen

### ISSUE THREAD

**Issue by sylware** [JFreegman/toxic#394]
video call displays in preview and sends to the connected friend, a green, top garbled, video.
Is there any contraints on the webcam (mine is a logitech C615) mode in order to make toxic operate properly on v4l data output (have not checked the code, my bad for asking here).

**Comment by ElLamparto** [comment]
I have exactly the same issue.

**Comment by metala** [comment]
Can you reproduce it with the latest master?

**Comment by ElLamparto** [comment]
The video works. Congratulations! (TOXIC v0.7.0-53-gcb21672-obs).
It would be great if the video window were re-sizable.

**Comment by metala** [comment]
Yeah, that would be nice, but it's not currently something that bothers me. I have other issues to fix for myself first. I will pull them here when I am finished.
