### ISSUE TITLE
Detaching a tmux instance with toxic running inside causes toxic to exit

### ISSUE THREAD

**Issue by HalosGhost** [JFreegman/toxic#397]
When running `toxic` under `tmux`, if I ever detach from the `tmux` session, upon reattachment, `toxic` has exited without warning.

**Comment by JFreegman** [comment]
Strange, that doesn't happen for me. Any further details about your environment that might be helpful?

**Comment by HalosGhost** [comment]
Let me take another look at it; I recently updated toxic to HEAD again because it added terminal-bell support which was something I sorely needed. If it is still an issue, I will try to give as much detail as I can.

**Comment by HalosGhost** [comment]
Indeed, it looks like this issue is no longer present for me either. Thanks for all your work!
