### ISSUE TITLE
How to setup audio and voice calls?

### ISSUE THREAD

**Issue by dmos62** [JFreegman/toxic#398]
toxic.conf man page says `referred audio input device; numbers correspond to /lsdev in`. It is unclear to me what `/lsdev in` means, it doesn't seem to be a command in toxic, or the linux command because it doesn't take arguments (right?). I tried to have toxic called, but toxic showed no notification of an incoming call, and I didn't seem to have any options to call a contact. I presume that's because audio is not setup?

So the issue is it is unclear how to setup toxic for voice calls.

**Comment by JFreegman** [comment]
`/lsdev in` is a toxic command. Usually things will work without setup, but it sounds like your toxic might not support A/V. Which package are you using?

**Comment by dmos62** [comment]
@JFreegman you helped me with this on freenode. The problem was that the debian package was compiled without a/v.

**Comment by DJJ88** [comment]
Hello  
I got the same problem. It seams but I don't see what I've done wrong.
could you tell how to fix this issue please?

**Comment by dmos62** [comment]
My distribution's package was compiled without audio/video support. I had
to compile it myself.
