### ISSUE TITLE
Very small video on videocall

### ISSUE THREAD

**Issue by alexeysvrv** [JFreegman/toxic#404]
When you turn on the video, there is a very small window with an outgoing video and at the same time within the video stream, as I call Ehobot. OS Ubuntu 14.04, Toxic version from the repository to the latest Jenkins. Thank you. I enclose screenshots
Incidentally, by increasing the window, its stretching, the video does not increase, and the remaining space in the box is filled with black.
![-240](https://cloud.githubusercontent.com/assets/15014747/17545252/cfe1e682-5ee4-11e6-8f03-19153f15a901.png)
![-239](https://cloud.githubusercontent.com/assets/15014747/17545253/cfe3f602-5ee4-11e6-8d24-b91684673a26.png)

**Comment by metala** [comment]
Easy solution is to disable the resizing on the window. Otherwise you have to write down the resizing of the image. You may take the one from utox, th's quite ugly, because it does not keep the ratio.

**Comment by alexeysvrv** [comment]
@metala How do I do that the image in full screen or half screen?

**Comment by metala** [comment]
If you can code it yourself, here is the scaling in uTox: https://github.com/GrayHatter/uTox/blob/develop/src/xlib/video.c

```
    /* scale image if needed */
    uint8_t *new_data = malloc(attrs.width * attrs.height * 4);
    if (new_data && (attrs.width != width || attrs.height != height)) {
        scale_rgbx_image(img_data, width, height, new_data, attrs.width, attrs.height);
        image.data = (char*)new_data;
    }
```

If it's just one off you may try to hardcode it here:
https://github.com/JFreegman/toxic/blob/master/src/video_device.c

```
        /* Setup video format */
        struct v4l2_format fmt;
        memset(&(fmt), 0, sizeof(fmt));

        fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        fmt.fmt.pix.pixelformat = V4L2_PIX_FMT_YUYV;
        if( -1 == xioctl(device->fd, VIDIOC_S_FMT, &fmt) ) {
            close(device->fd);
            free(device);
            unlock;
            return vde_FailedStart;
        }
```

**Comment by alexeysvrv** [comment]
@metala I'm not a developer, I'm a regular user. It is necessary to wait for the correction in the code?

**Comment by metala** [comment]
@alexeysvrv Well then.. I cannot help at the moment, if you can lure someone else to fix it, it would be wondeful. Try using qTox/uTox instead. In most cases you don't expect video in console-based application, so it's quite unusual for toxic and pretty awesome that it has even support of video calls.

**Comment by alexeysvrv** [comment]
@JFreegman You can fix it?

**Comment by alexeysvrv** [comment]
@JFreegman Any progress?

**Comment by JFreegman** [comment]
You might want to ask @mannol about this, I didn't work on Toxic's video.

**Comment by alexeysvrv** [comment]
@mannol You can help?

**Comment by eaterjolly** [comment]
Implementing #126 could relate here. 

Making a line in the conf file to specify aa view or windowed-picture view.

**Comment by alexeysvrv** [comment]
@eaterjolly Please, help with this issue

**Comment by krasjev** [comment]
Hi. 

I recently started to use Toxic which I really like. 

The only drawback I could find so far is the very small video size.

Is there any chance to have this fixed? That would be really awesome! 

If a fix for dynamic resizing is not an option I would already be very happy if the initial default size was twice as big.

My toxic:
Toxic version 0.8.2_r1820
Toxcore version 0.2.2

I'd be happy to help testing.

Thank you very much!

**Comment by JFreegman** [comment]
You can now use the `/res` command to change the size of the window. You need to do that before you start the call for it to take effect.
