### ISSUE TITLE
Repeated freezes and non-responsiveness

### ISSUE THREAD

**Issue by kozross** [JFreegman/toxic#406]
Toxic has been having repeated non-responsive freezes, lasting a minute or more, over and over again, during its typical run. Other users say that I 'blink' on and offline repeatedly, and I see them blinking the same way (when Toxic finally responds). I've attached the results of a -b log to this bug report.

I'm on Toxic 0.7.0-5 from the Parabola GNU/Linux-libre repos.  My toxcore is listed as 3747-2, from the community repository of Parabola (which it has in common with Arch, at least for this package anyway). 

[toxic-errordump.txt](https://github.com/JFreegman/toxic/files/451851/toxic-errordump.txt)

**Comment by JFreegman** [comment]
Are you still having this problem while on the latest commit?

**Comment by kozross** [comment]
The latest commit fixes these issues - thank you!

**Comment by JFreegman** [comment]
Cool, I think it might've been due to really slow DNS requests during bootstrapping.

**Comment by kozross** [comment]
Seems it was premature of me - after ~2 hours of continuous use, it started doing the same things again. To clarify, waht changed is that the onset of the problem is longer, and the non-frozen periods are a bit longer, but the freezes still occur.

**Comment by JFreegman** [comment]
Strange. If you know how to use GDB you could try breaking during a freeze to see what function it's frozen in. Otherwise I have no idea what might be causing that.
