### ISSUE TITLE
Switch to c-toxcore

### ISSUE THREAD

**Issue by NicoHood** [JFreegman/toxic#418]
Hi,
will this project switch to c-toxcore as it is the new upstream toxcore source now? Every other tox client switches to c-toxcore over time now and it would be essential for you to do so too if people want to use tuntox in their linux distribution.

**Comment by JFreegman** [comment]
Yes, I'm currently working on making the switch.

**Comment by JFreegman** [comment]
Done.

**Comment by NicoHood** [comment]
Great. Can you please also sign the release? #417

**Comment by JFreegman** [comment]
Done.

**Comment by NicoHood** [comment]
Thanks a lot!
