### ISSUE TITLE
TokTok/c-toxcore or irungentoo/toxcore

### ISSUE THREAD

**Issue by thierry-FreeBSD** [JFreegman/toxic#420]
Version 0.7.2 does not compile out of the box against toxcore from irungentoo/toxcore, but it needs TOX_CONFERENCE symbols from TokTok/c-toxcore.

Is TokTok/c-toxcore considered as the new "official" toxcore?

**Comment by thierry-FreeBSD** [comment]
Sorry, duplicate of #419.

**Comment by JFreegman** [comment]
>Is TokTok/c-toxcore considered as the new "official" toxcore?

Yep
