### ISSUE TITLE
missing fflush() in dialogues

### ISSUE THREAD

**Issue by x368** [JFreegman/toxic#422]
For the background see e.g. http://www.openwall.com/lists/musl/2016/02/10/6
by Rich Felker: "ISO C permitted and even encouraged (but made optional) a
behavior whereby attempting to read from a line-buffered input stream
causes all line-buffered output streams to be flushed. While this is
convenient for programmers who write prompt strings not ending in
newlines, and who don't want to be bothered with calling fflush, this
feature was conceived in an era where C did not have multi-threading,
and providing it when you have threads imposes a heavy synchronization
burden and can even lead to deadlock. Therefore musl does not do it.
So if you want to print prompt strings that don't end in a newline,
and have them appear before input is read, you have to use fflush
yourself."
IOW the code is relying on an optional/suboptimal libc behaviour and the result looks unfortunately badly broken given a well conformant musl libc (the first start of the program yields nothing else than a blank page). The fix is needed in all stdio-based dialogues where the prompt does not end in '\n'.
Thanks for your work on toxic!

**Comment by x368** [comment]
possibly something like the following would be sufficient

    --- src/toxic.c.orig
    +++ src/toxic.c
    @@ -382,6 +382,7 @@
         do {
             system("clear");
             printf("%s ", msg);
    +        fflush(stdout);
     
             if (!strcasecmp(ch, "y\n") || !strcasecmp(ch, "n\n") || !strcasecmp(ch, "yes\n")
                     || !strcasecmp(ch, "no\n") || !strcasecmp(ch, "q\n"))
    @@ -400,6 +401,7 @@
             char passconfirm[MAX_PASSWORD_LEN + 1] = {0};
     
             printf("Enter a new password (must be at least %d characters) ", MIN_PASSWORD_LEN);
    +        fflush(stdout);
     
             while (valid_password == false) {
                 len = password_prompt(user_password.pass, sizeof(user_password.pass));
    @@ -410,11 +412,13 @@
     
                 if (string_is_empty(passconfirm) && (len < MIN_PASSWORD_LEN || len > MAX_PASSWORD_LEN)) {
                     printf("Password must be between %d and %d characters long. ", MIN_PASSWORD_LEN, MAX_PASSWORD_LEN);
    +                fflush(stdout);
                     continue;
                 }
     
                 if (string_is_empty(passconfirm)) {
                     printf("Enter password again ");
    +                fflush(stdout);
                     snprintf(passconfirm, sizeof(passconfirm), "%s", user_password.pass);
                     continue;
                 }
    @@ -423,6 +427,7 @@
                     memset(passconfirm, 0, sizeof(passconfirm));
                     memset(user_password.pass, 0, sizeof(user_password.pass));
                     printf("Passwords don't match. Try again. ");
    +                fflush(stdout);
                     continue;
                 }
     
    @@ -621,6 +626,7 @@
                 if (!pweval) {
                     system("clear");   // TODO: is this portable?
                     printf("Enter password (q to quit) ");
    +                fflush(stdout);
                 }
     
                 size_t plain_len = len - TOX_PASS_ENCRYPTION_EXTRA_LENGTH;
    @@ -644,6 +650,7 @@
                         system("clear");
                         sleep(1);
                         printf("Invalid password. Try again. ");
    +                    fflush(stdout);
                         pweval = 0;
                         continue;
                     }
    @@ -669,6 +676,7 @@
                         system("clear");
                         sleep(1);
                         printf("Invalid password. Try again. ");
    +                    fflush(stdout);
                         pweval = 0;
                     } else {
                         fclose(fp);

**Comment by JFreegman** [comment]
Addressed in https://github.com/JFreegman/toxic/pull/430

If that didn't work let me know and I'll reopen the issue.
