### ISSUE TITLE
Toxic session aborted with error code 9 (tox_new returned fatal error)

### ISSUE THREAD

**Issue by CaptainKraft** [JFreegman/toxic#424]
Start toxic, type password to decrypt, immediately get this message and return. This also happens for an unencrypted profile as well as new and old profiles.

I'm on Arch 64 bit and this started after a system update. The machine my toxic runs on hadn't been updated in a while, so it might be tricky to track down which of the many updates caused this.

**Comment by JFreegman** [comment]
The toxcore API specifies this error as:

>     /**
>      * The data format was invalid. This can happen when loading data that was
>      * saved by an older version of Tox, or when the data has been corrupted.
>      * When loading from badly formatted data, some data may have been loaded,
>      * and the rest is discarded. Passing an invalid length parameter also
>      * causes this error.
>      */

To determine if this is a toxic-specific issue, try recreating the problem in another client such as qtox or utox.

**Comment by CaptainKraft** [comment]
I see. Looks like I got an upgraded toxcore but not toxic. Problem solved, thank you.
