### ISSUE TITLE
Bug with log files.

### ISSUE THREAD

**Issue by MrSorcus** [JFreegman/toxic#425]
`2017/01/16 [09:14:15] Sorcus: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/www.example.org/fullchain.pem") failed - какого хрена веста ищет server.inwebse.org директорию?`

If this line exist in log file, all new messages will be printed behind input text area.

**Comment by JFreegman** [comment]
Can you please elaborate on how this is related to Toxic?

Edit: Oh, I see you're referring to Toxic's chat logs. I'm going to need some more context.

**Comment by MrSorcus** [comment]
To reproduce:
1. Set `history_size=80;`
2. Replace any user log file (for example TestFriend) to this https://gist.github.com/DebugReport/e65a147a7f869f54c14fc41712947058
3. Start Toxic and open chat with TestFriend.

**Comment by JFreegman** [comment]
I'm unable to reproduce this bug using the steps above. What terminal emulator are you using? Version of Toxic? OS? Are you running it through something like Screen or Putty?

**Comment by DebugReport** [comment]
konsole 16.12.1

**Comment by MrSorcus** [comment]
Toxic Version  : 0.7.1_r1741
Konsole Version 16.12.1
Linux laptop 4.9.0-1-ARCH #1 SMP PREEMPT Thu Dec 22 13:21:10 CET 2016 x86_64 GNU/Linux

Screenshots:
http://meson.ad-l.ink/private/6WjYJ2KZZ/c7cebd9fe5881a5cb0718574514d1105/image.png (Incorrect)
On first screen i can't see line `Logging for this window is ON; type "/log off" to disable. (Logs are not encrypted)`
http://meson.ad-l.ink/private/7C7nlxv8w/0511982acd7b64b787a4415ac0255ed5/image.png (Correct)
Next screen show how sending messages work. 
http://meson.ad-l.ink/private/6mpXbnj5J/1908d2c54f10b6015ed3fae5d98fd2b3/image.png (write message)
http://meson.ad-l.ink/private/6NYHLR2qj/2fb1595f51b42551444f581fc2134df7/image.png (After sending, you can see, that show me line `Logging for...`, but not my message `Test Message (1)`
http://meson.ad-l.ink/private/6qlWplb5q/2cbabc22dd1441154b46d66b38cf9656/image.png (write second message)
http://meson.ad-l.ink/private/7skMwwmMV/8a4a06c0c3a049d8209efb7f30d383b5/image.png (send)
http://meson.ad-l.ink/private/77pLbVDDW/c0efe4a65bf1e2b463a60ad8034b905b/image.png (write third message)
http://meson.ad-l.ink/private/7w5zXJC4P/4d7a79a41f2e46334a64a26b6eef807b/image.png (send)

**Comment by JFreegman** [comment]
Ah this is an old ncurses bug that I never figured out how to fix. Sometimes for some reason the window doesn't scroll automatically on input. All you need to do is manually scroll the window down (default is ctrl+v)

**Comment by MrSorcus** [comment]
Oh, ok. Thanks you :-)

**Comment by JFreegman** [comment]
Sorry, I meant to say the default is the page down button. Ctrl+V will scroll it half a page. You can change these bindings in the config file.
