### ISSUE TITLE
Supported OS missing at tox.chat website: Ubuntu Touch

### ISSUE THREAD

**Issue by b2000699** [JFreegman/toxic#426]
Hi,

Ubuntu Touch runs a regular Linux kernel, but a different windows server than the normal desktop edition of Ubuntu. For this reason, all Linux CLI programs run under Ubuntu Touch as on any other Linux desktop machine, but not GUI programs, since they require the X server.

Thus, since toxic is not using any X-server but only the command line based NCURSES as a GUI, toxic should perfectly run on Ubuntu Touch, too, isn't it?

If yes, then toxic runs on a whole bunch of smartphones and tablets out there, which are supported by Ubuntu Touch and I think for this reason Ubuntu Touch should be added to all officially supported OS lists, such as
- https://tox.chat/clients.html and
- https://wiki.tox.chat/clients

Cheers.

P.S.: For further reading:
- https://wiki.ubuntu.com/Touch/FAQ#Which_applications_do_run_on_Ubuntu_Touch.3F
- https://askubuntu.com/questions/417891/can-i-install-and-run-native-gui-linux-apps-on-ubuntu-touch

**Comment by JFreegman** [comment]
This issue belongs in the tox.chat repo: https://github.com/Tox/tox.chat
