### ISSUE TITLE
encrypt toxic chat logs

### ISSUE THREAD

**Issue by aparcar** [JFreegman/toxic#429]
I'm using tox with a startup password.
However, storing all chat logs decrypted looks like a huge pitfall for privacy.
Is it possible to encrypt all logs with the startup password?

**Comment by JFreegman** [comment]
Toxic does not have log encryption at the time being. If you're worried, I'd suggest either using full disk encryption, or disabling logging.

**Comment by GrayHatter** [comment]
Looking into how every filesystem does disk read writes. If this is something you might ever want. The ONLY method that would be beneficial is full disk encryption.
