### ISSUE TITLE
Cannot use existing .tox file; -f overwrites

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#431]
I am having an issue wherein, after wiping an old computer and installing a different distro, I am unable to port my existing Tox ID.

I have tried placing the .tox file in the normal directory, as well as booting it from other directories. It overwrites the file, and when I check my ID, it's a newly generated file. I have also tried replacing said file that -f created with the one containing my desired ID.

What's odd is I had ported this ID from a GUI client, and had used it on my previous distro using the same -f command without issue. Not sure which version I was using then, currently on 0.7.2.

Please let me know if you need any more detail, or if you have suggestions for other methods to try or workarounds. I'd really love to stay with a TUI but will use GUI if I am unable to get my ID functioning under this client.

**Comment by JFreegman** [comment]
Have you double checked that your old profile has the correct owner/permissions? Have you tried using it with a third client to see if it's a toxic-specific issue or not?

**Comment by ghost** [comment]
I have discovered the error.

I thought that I had made an exact replica of the .tox file that I am trying to load, but it does not look as if I did (I could have sworn - maybe it's hiding somewhere; if I do find it and get it to work I'll update this.) Instead, what I have is a file marked .tox that's just the string that encompasses my user ID.

Is there any way to convert this into an actual .tox file? I cannot seem to find that option under the actual tox binary, and I assume that this function was not built into toxic.

Apologies - error is on my end. If you are aware of any solutions or workarounds, I'd be much obliged.

**Comment by JFreegman** [comment]
>Instead, what I have is a file marked .tox that's just the string that encompasses my user ID. Is there any way to convert this into an actual .tox file?

Your Tox ID is just the public half of your profile's cryptographic key pair. You would need your private key as well, but even then there are no tools that do this automatically to my knowledge (though it would be pretty easy to make one).

I'm going to close this issue as it's not toxic specific.
