### ISSUE TITLE
Text selection not working

### ISSUE THREAD

**Issue by UralZima** [JFreegman/toxic#433]
Hi. I am using latest toxic. I using it more about 2 years, and text selection never worked.
I use it in Konsole app (KDE), running in GNU screen. It is unable to select text to copy it to clipboard.
When I need to copy text, I open a new Konsole window, do 'screen -r', and there I can select it temporarily, while I click something or move to another toxic window. Then I switch back in my first window with 'screen -r'. 
Is there any way to enable text selection? Why it is working on just-resumed screen in other konsole and then stops?

Thanks. 
Toxic is awesome

**Comment by JFreegman** [comment]
I'm not sure what's causing this problem, but you could try the following:
- Use the no-X11 version of Toxic (you will no longer have video)
- Use tmux instead of screen
- Use a different terminal emulator

**Comment by UralZima** [comment]
I have reported this bug to konsole. Can you tell some more info for it's devs? Like what libs used, ncurses etc. Thanks
