### ISSUE TITLE
External Password Source

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#434]
This is a feature request.

Would it be hard to implement a config options that makes toxic when starting with an encrypted profile take the password from a pipe ? I keep all my passwords in pass and I would love to just "pass tox |" automatically everytime I start toxic, similar to how I handle passwords in mutt.

**Comment by JFreegman** [comment]
Have you tried the `password_eval` config option? See `man toxic.conf`

**Comment by ghost** [comment]
I just tried it it works like a charm. I didn't even think of checking man toxic.conf since I thought all the options already enumerated inside the config file.
