### ISSUE TITLE
Issues and Questions

### ISSUE THREAD

**Issue by Artysteel** [JFreegman/toxic#439]
Good day,

I've installed toxic core, dependencies, and Toxic.
Starting it from build/toxic via sudo ./toxic

It comes online after few seconds.

- How to make TOX ID not to change? (It does change for me each time I restart the program, contact list is empty as well after that)
- Is it possible to make a video call from terminal, using Tox libraries, if yes, could you please show me and example or a link. Could not find that info, sadly.

- How video works exactly? I've called my phone audio works great, as soon as i type /video (sia) ssh it kinda hangs. I am not using any GUI. Do I need to?

**Comment by JFreegman** [comment]
>Starting it from build/toxic via sudo ./toxic

You should install it with `make install` and then run it with `toxic`

>How to make TOX ID not to change? (It does change for me each time I restart the program, contact list is empty as well after that)

That means that toxic doesn't have write permissions

>Is it possible to make a video call from terminal, using Tox libraries, if yes, could you please show me and example or a link. Could not find that info, sadly.

Toxic's video uses X windows.

**Comment by Artysteel** [comment]
Thanks for answers, appreciated!
