### ISSUE TITLE
Make personal note permanent

### ISSUE THREAD

**Issue by FriedrichFroebel** [JFreegman/toxic#440]
Currently, setting a note by using `/note "myNote"` seems to be resetted after restarting the Toxic client so it ends up with `Toxing on Toxic` again. Other Tox clients set this note permanently which is better in my opinion.

**Comment by JFreegman** [comment]
The note should be permanent. This would indicate a saving issue. Is anything else not saving, such a your nick or new contacts?

**Comment by FriedrichFroebel** [comment]
My nick and new contacts are saved without problems.

**Comment by JFreegman** [comment]
What's the note you're trying to set? If it's zero length it will set the default note.

**Comment by FriedrichFroebel** [comment]
I am using `"myNote"` for testing.

**Comment by FriedrichFroebel** [comment]
Seems like it works now with the new version (do not know if the update is the reason for this or not).
