### ISSUE TITLE
"File not found" error when using home directory shortcut

### ISSUE THREAD

**Issue by FriedrichFroebel** [JFreegman/toxic#442]
Trying to send a file in a chat using `/sendfile "~/myFile.txt` fails with a `File not found.` on Ubuntu. Using `/sendfile "/home/me/myFile.txt"` (which points to the same file) runs without problems.

**Comment by JFreegman** [comment]
Toxic doesn't recognize `~/` but you can tab-complete it and it will auto-convert to the full path.

**Comment by FriedrichFroebel** [comment]
A somehow unexpected behavior, but knowing it now (and having seen that the home directory is the default base directory) I can use it this way.
