### ISSUE TITLE
TUI rearrangement suggestion

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#450]
Would you consider merging the contacts and the home tab ? It would also be a lot easier to interact with contacts using commands instead of an additional set of keys that you only use for a tab.

I don't have the time (and the skills probably) required to do a pull request at the moment, I'm posting this just as an idea in case toxic contributors think about this in the future.

Please feel free to close this at any time.

**Comment by JFreegman** [comment]
I don't think I would consider doing this for a number of reasons, foremost because I don't think it would be a UX improvement.

**Comment by ghost** [comment]
Well I guess I must have used weechat too much or something. (and yes I know there's a tox plugin for weechat). It might have been premature to make this issue. I'll think a bit about this because right now it just feels like I'm imposing familiar patterns on other people's work.

**Comment by ghost** [comment]
I'm closing this since I couldn't find feasable arguments for toxic in it's current state.
