### ISSUE TITLE
How to unblock a contact?

### ISSUE THREAD

**Issue by UralZima** [JFreegman/toxic#451]
Hello. I am using Toxic 0.7.2. I have blocked a contact using 'b' key.
The help says, with that key I can block/unblock contact. But the contact was disappeared and I don't know how to unblock it. Please help

**Comment by JFreegman** [comment]
Switch to the block list using the left and right arrow keys, then select the blocked contact and hit the b key again.

**Comment by UralZima** [comment]
Thank you!
