### ISSUE TITLE
Offline messages

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#455]
Is there a reason there isn't an option for the current pseudo-offline messaging mode to extend beyond client shutdown ( assuming toxic has something like this, I'm not so sure ) ? Having the "to be sent" messages stored in a log on my machine and automatically sent and deleted when a contact is online doesn't seem like a bad idea.

**Comment by shamlabanana** [comment]
Hey, I'm going to hijack this to ask a question which is somewhat related to what op asked.

I've been using ratox for a while and I recommended toxic to one of my friends but he says I don't receive messages after I'm coming online after he sent them and remained online.

Does toxic not have https://wiki.tox.chat/users/offline_messaging ?

**Comment by JFreegman** [comment]
Toxic does have pseudo-offline messages. The messages will not send if you close the contact's window before they come online, or if you close the client.
