### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#457]
Hi,

Will you guys also be creating a windows client, I currently use windows I love toxic because I tried it on Linux but there is no support for windows :(

**Comment by GrayHatter** [comment]
it runs fine on W10 inside of cygwin

**Comment by JFreegman** [comment]
There are currently no plans to port Toxic to Windows, but like GrayHatter said, cygwin usually works well.

**Comment by ghost** [comment]
Thanks
