### ISSUE TITLE
Bell notifications not working

### ISSUE THREAD

**Issue by junaru** [JFreegman/toxic#459]
Looks like terminal bell notifications are not working.
If we execute ` $ sleep 3 && echo ^G ` (thats ^V^G) in tmux and switch windows, tmux will highlight the window that produced bell:

![sc1](https://user-images.githubusercontent.com/59161/29612185-095fe0c8-8809-11e7-98e4-be092361f61f.png)

This however does not happen when someone messages you and you have `bell_on_message=true` in your toxic.conf

```
$ tmux -V
tmux 2.5
$ toxic --version
Toxic version 0.7.2
Toxcore version 0.1.9
$ echo $TERM
screen-256color
```

**Comment by dou4cc** [comment]
any progress?

**Comment by jhe2** [comment]
I have noticed this issue as well. It appears only when Toxic has been compiled with X11 support (which is common for distro packages), but is run in a non-X11 environment. I have created a pull request to fix this issue: https://github.com/JFreegman/toxic/pull/540

**Comment by JFreegman** [comment]
This issue has hopefully been fixed in https://github.com/TokTok/toxic/pull/88. If not I can re-open this issue.
