### ISSUE TITLE
What about using libyui? TUI+GUI in one!

### ISSUE THREAD

**Issue by timofonic** [JFreegman/toxic#460]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by wobbol** [comment]
Given the amount of activity in toxic, I think this is probably out of scope. If you are willing to port toxic to libyui or know someone willing to, I recommend speaking directly with the author/maintainer. @JFreegman seems to be both of those.

**Comment by JFreegman** [comment]
Writing a graphical interface for Toxic would be a pretty big job and it's not something I have time for these days. It's not really within the scope of the project either; there are plenty of functioning graphical clients for Tox already.
