### ISSUE TITLE
Filter out \r before sending messages

### ISSUE THREAD

**Issue by Sorunome** [JFreegman/toxic#462]
If messages contain \r it can lead to pretty weird stuff, such as , such as

```
19:53:10 --- Sorunome: lel

now I can be spooky

I wonder who's talking
19:53:26 --- Vulpix: not me
19:53:36 --- Vulpix: :p
```
Where Vulpix actually sent the "now I can be spooky" and "I wonder who's talking"

**Comment by LittleVulpix** [comment]
Lies, I sent nothing. It must be ghosts.

But yeah, it is as @Sorunome says. My client is Miranda NG @ Windows, but for example when I send the same message to qtox, qtox deals with it just fine.

**Comment by JFreegman** [comment]
This is intended behaviour. Messages are supposed to be displayed as they're received per https://tox.gitbooks.io/tox-client-standard/content/communication/message_formatting.html

**Comment by Sorunome** [comment]
How is it inteded that the messages by vulpix lack the timestamp when they were recieved along with that vulpix posted them at all?

**Comment by JFreegman** [comment]
The timestamp is printed by the client and not received in the actual message.

**Comment by Sorunome** [comment]
Yes, and exactly that is missing, thus the bug report. Vulpix and me tracked it down with different test things and it appears that a trailing \r (which isn't followed by a \n) or similar causes this behaviour. Check again the first post, what i posted was exactly what i saw in the terminal, while I only wrote the message "lel", and nothing more

**Comment by JFreegman** [comment]
Ok I see the issue, I'll take a look at it. @LittleVulpix can you give me the raw input for that message?

**Comment by JFreegman** [comment]
Fixed: https://github.com/JFreegman/toxic/commit/80c05002991bb2444e0b7dd53eb8957d68fafa3d
Let me know if there are any further issues with this.
