### ISSUE TITLE
toxic no longer redraws on term windows resize

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#463]
I know this was not intended as I read into an issue but if this is considered a bug what information can I provide ?

**Comment by JFreegman** [comment]
Can you provide your terminal emulator, toxic version, operating system, and third party software that you use with it? Also do you know when this began happening?

**Comment by ghost** [comment]
I just started using it again fater I've used ratox a while. I'm sorry I don't know when this was introduced.

term: https://aur.archlinux.org/packages/xst-git/
toxic: https://www.archlinux.org/packages/community/x86_64/toxic/

I also tried toxic-git from AUR. If you haven't noticed this already I think it's probably xst's fault.

**Comment by JFreegman** [comment]
Since this issue only seems to be a problem with xst the best I can do is recommend you use toxic with a different terminal emulator

**Comment by ghost** [comment]
You're right I just tested and this doesn't appear with simply st.

**Comment by ghost** [comment]
Ok this actually happens on st also.Does the same logic apply regarding switching to another term emulator apply ? st is fairly popular.

**Comment by ghost** [comment]
Here's my config.def.h in case you're willing to give any time to this.
http://ix.io/zz1
I basically just change the colors and the font.

**Comment by ghost** [comment]
Downgrading to ncurses 6.0+20170527-1 from 6.0+20170827-1 solves this. Maybe the st terminfo since that is not handled by the official st package it's left for ncurses and toxic doesn't seem to depend on ncurses.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/st

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/ncurses&id=bdb8a4d0db5b229de3ecccc5d48d2c3720dc008b

**Comment by ghost** [comment]
This was solved in: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/ncurses&id=e7db9e7e6b42a6ef2c071cd8059051090930235b
