### ISSUE TITLE
gcc (GCC) 7.1.1 cmpilation warnings

### ISSUE THREAD

**Issue by mrkiko** [JFreegman/toxic#464]
Script started on 2017-09-01 21:12:37+0200
[mrkiko@gatosaldo toxic]$ make
  CC    autocomplete.o
/home/mrkiko/files/srcs/toxic/src/autocomplete.c: In function dir_match:
/home/mrkiko/files/srcs/toxic/src/autocomplete.c:297:70: warning: snprintf output may be truncated before the last format character [-Wformat-truncation=]
             snprintf(dirnames[dircount], sizeof(dirnames[dircount]), "%s", entry->d_name);
                                                                      ^~~~
/home/mrkiko/files/srcs/toxic/src/autocomplete.c:297:13: note: snprintf output between 1 and 256 bytes into a destination of size 255
             snprintf(dirnames[dircount], sizeof(dirnames[dircount]), "%s", entry->d_name);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC    avatars.o
  CC    bootstrap.o
  CC    chat.o
/home/mrkiko/files/srcs/toxic/src/chat.c: In function chat_onFileRecv:
/home/mrkiko/files/srcs/toxic/src/chat.c:569:49: warning: %s directive output may be truncated writing up to 4095 bytes into a region of size 1372 [-Wformat-truncation=]
         snprintf(file_path, sizeof(file_path), "%s%s", user_settings->download_path, filename);
                                                 ^~
/home/mrkiko/files/srcs/toxic/src/chat.c:569:9: note: snprintf output 1 or more bytes (assuming 4096) into a destination of size 1372
         snprintf(file_path, sizeof(file_path), "%s%s", user_settings->download_path, filename);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...
  CC    term_mplex.o
  CC    toxic.o
/home/mrkiko/files/srcs/toxic/src/toxic.c: In function init_tox_options:
/home/mrkiko/files/srcs/toxic/src/toxic.c:582:52: warning: %s directive output may be truncated writing up to 255 bytes into a region of size 35 [-Wformat-truncation=]
         snprintf(tmp, sizeof(tmp), "Using %s proxy %s : %d", ps, [32m[Karg_opts.proxy_address, arg_opts.proxy_port);
                                                    ^~            [32m[K~~~~~~~~
/home/mrkiko/files/srcs/toxic/src/toxic.c:582:9: note: snprintf output 18 or more bytes (assuming 273) into a destination of size 48
         snprintf(tmp, sizeof(tmp), "Using %s proxy %s : %d", ps, arg_opts.proxy_address, arg_opts.proxy_port);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mrkiko/files/srcs/toxic/src/toxic.c: In function main:
/home/mrkiko/files/srcs/toxic/src/toxic.c:1260:55: warning: %s directive output may be truncated writing up to 4095 bytes into a region of size 1363 [-Wformat-truncation=]
     snprintf(avatarstr, sizeof(avatarstr), "/avatar \"%s\"", user_settings->avatar_path);
                                                       ^~
/home/mrkiko/files/srcs/toxic/src/toxic.c:1260:5: note: snprintf output between 11 and 4106 bytes into a destination of size 1372
     snprintf(avatarstr, sizeof(avatarstr), "/avatar \"%s\"", user_settings->avatar_path);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
  CC    video_device.o
  LD    toxic
[mrkiko@gatosaldo toxic]$

GCC version:
gcc (GCC) 7.1.1 20170630
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This is a 32-bit Archlinux, up to date, glibc 2.25, pkg revision 4

**Comment by JFreegman** [comment]
Must be a new compile flag because neither my version of GCC or Clang recognize it. Anyhow, fixed (let me know if the warnings don't go away): https://github.com/JFreegman/toxic/commit/f2c116feb3bd14c357361a8b0221ee8865a0f681

**Comment by mrkiko** [comment]
Thank you very very much for your great work and all.
Enrico
