### ISSUE TITLE
segfault on calling friend with friend_number >= 10

### ISSUE THREAD

**Issue by zugz** [JFreegman/toxic#476]
This happens because we use CallControl.calls[friend_number],
e.g. at audio_call.c:418,
but CallControl.calls has length MAX_CALLS = 10.

Oops.

**Comment by JFreegman** [comment]
Should be fixed: https://github.com/JFreegman/toxic/commit/a5a1f6015df15d73f12f6d7bbbd968d79e5352e3

**Comment by zugz** [comment]
* Monday, 2017-11-20 at 12:04 +0000 - JFreegman <notifications@github.com>:

>Should be fixed: https://github.com/JFreegman/toxic/commit/a5a1f6015df15d73f12f6d7bbbd968d79e5352e3

Excellent. It looks and works fine. Good stuff!
