### ISSUE TITLE
Accepting aborted file transfer creates an empty file

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#477]
Pseudolog:
```
13:37:00 --- Bob: I want to test something.
13:37:01 --- Bob: You create a file transfer, go out and then come back online, again.
13:37:02 --- Bob: I will accept the file transfer, after you come back.
13:37:03 --- Bob: I think the transfer will fail immediately, but toxic will still create an empty file.
File transfer request for 'file.ext' (n.m KiB)
Type '/savefile 1' to accept the file transfer.
File transfer for 'file.ext' was aborted.
13:37:10 <-- Alice has gone offline
13:37:20 --> Alice has come online
File transfer failed: Invalid filenumber.
```

```
$ wc --bytes file.ext
0 file.ext
```

What I would expect:
The file will not be created in the first place.

If file creation can't be avoided, then file deletion would be a dirty hack.

**Comment by JFreegman** [comment]
This is intended behaviour. It's not practical to wait for the file transfer to begin before creating the file, and I don't think it's correct behaviour for a client to automatically delete incomplete files.

**Comment by ghost** [comment]
Ok.

What do you think about giving incomplete files the ".part" extension?

**Comment by JFreegman** [comment]
That's not a bad idea. I'll look at it and possibly implement it if I can find the time
