### ISSUE TITLE
Toxic does not go online.

### ISSUE THREAD

**Issue by a0000000** [JFreegman/toxic#482]
Before some days, toxic generated `toxic_profile.tox`, that go online.
With an old `toxic_profile.tox`, toxic still go online.
But now, toxic does not generate `toxic_profile.tox`, that go online.

(If toxic run, and then start utox, go toxic online.
Besides, becomes `toxic_profile.tox` bigger.
But I think, then this is, a faulty connection.)

Is maybe absent, a package?

### OS:
Devuan Jessie 1.0.0 i386
(https://files.devuan.org/devuan_jessie)

### Install Toxic and libqrencode3
`apt-get install libqrencode3`
`wget https://pkg.tox.chat/debian/pool/release/t/toxic-no-x11/toxic-no-x11_0.8.1-299_i386.deb`
`dpkg -i toxic-no-x11_0.8.1-299_i386.deb`

I have tried it also, with the installation, all these packages:
apt-get install libsodium13
apt-get install libopus-dev libsodium-dev libvpx-dev
https://pkg.tox.chat/debian/pool/jessie/libt/libtoxcore/
### Start Toxic (without existing `~/.config/tox/`):
`toxic`
Toxic does not go online.

### Start Toxic with `--debug` (without existing `~/.config/tox/`):
`toxic --debug`
Toxic write:
`HTTPS lookup error (libcurl error 7)`
`update_DHT_nodeslist() failed with error -2`
`nodeslist load error: file empty.`

**Comment by ghost** [comment]
I get the same errors here with my first toxic run, whatever option I use. Here being Gentoo with toxic 0.8.1 and toxcore 0.1.10.

**Comment by JFreegman** [comment]
This error is a result of https://nodes.tox.chat/ being down. I'll alert the maintainer. In the mean time, you can manually connect with the `/connect` command using nodes from https://wiki.tox.chat/users/nodes

edit: should be working now

**Comment by ghost** [comment]
I see, thanks. It'd be wise to print the IP/URL reponsible instead of just `HTTPS lookup error (libcurl error 7)`, though.

**Comment by a0000000** [comment]
> should be working now

Yes, now it works, thanks :D
