### ISSUE TITLE
Need help in using commands at toxic command prompt.

### ISSUE THREAD

**Issue by blprasad** [JFreegman/toxic#484]
Hi all, 
It's not an issue really. I don't know where  to ask so I am doing it here.

I am new to toxic . I am trying to explore toxic ,but have never used toxic so far. I searched for commands document and I could not find one.I need a document that explains how the proper usage of toxic command chat commands as well as global commands.If the document has examples how to use those commands then it's very useful to me. If some one gives some suggestions regarding this ,it's helpful. I tried with /add command but i could not figure out how to use it properly.I have not tried other commands yet.

thanks.

**Comment by JFreegman** [comment]
Type `/help` for a help menu that explains all the commands.

**Comment by blprasad** [comment]
Hi JFreegman,
thanks for the reply ,I already tried it that way. I may need to explore it more.

**Comment by blprasad** [comment]
In help/global  menu it shows Id and addr , bit confused here ,both are same it seems.

**Comment by JFreegman** [comment]
`ID` is an index that identifies friends in your pending friend requests, which you can see with the `/requests` command. `addr` is a Tox ID/address. To add someone by their Tox ID, it would look like `/add 56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855D34D34D37CB5`

**Comment by blprasad** [comment]
in execute.c  #ifdef AUDIO   , where to  enable or disable, is it in makefile? or is there any other approach.
and also I looked at INSTALL procedure there are variables like
DISABLE_X11=1 
DISABLE_AV=1
how to pass them i.e., enable and disable them, please help me here too.
i am not getting call,answer etc commands in my chat commands menu ,it may be due to #ifdef AUDIO  flag disabled. I am trying to grep these variables these are shown on .mk files .I dont have knowledge on .mk files.

**Comment by JFreegman** [comment]
You need to have all the appropriate libs installed per the dependencies list, and it will build with A/V support automatically.

**Comment by blprasad** [comment]
OK,got it now, they appeared after i installed dependecies.What is the  procedure to control these variables, if I want only audio call support and no video ,how can I do that ,does it need to modify the makefile accordingly? or pass them to make command or what? I am exploring the code to remove the video support, I am just commenting all the video functions for now.My requirement does not need video support for now.

**Comment by blprasad** [comment]
I am trying to make a voice call for testing purpose.I am trying using two systems run linux.One is similar to Raspberri Pi, another is my Ubundu laptop.I am able to establish a voice call . I am running a toxic instace on each of them.On both of them it shows call is active ,but I am unable to hear any voice.I am trying to speak from laptop and hear the same on Pi speaker. I hear only some hiss noise on Pi.When I try to mute my volume on laptop that noice is not heard anymore.I can only hear noice or nothing.I am still trying to figure out what is going wrong.Am I missing any speaker or mic settings? ,I appreciate any help.

**Comment by blprasad** [comment]
After few failed attempts, finally got it working as expected.
thanks
