### ISSUE TITLE
Question about SailfishOS support

### ISSUE THREAD

**Issue by Sami32** [JFreegman/toxic#485]
Hello,

sorry if it bother you, but i get confuse when i read the following informations that said that toxic work on SailfishOS and nothing related to it on your site:
https://wiki.tox.chat/include/clients_features
https://together.jolla.com/question/42578/tox-client-for-sailfishos/
https://talk.maemo.org/showthread.php?t=93729

So, do that mean that only old toxic version was able to work on SailfishOS ?
I'll appreciate any insight on that.

**Comment by JFreegman** [comment]
I don't know anything about SailfishOS, but if it's unix-like then there's a good chance it will work. I'd recommend either compiling Toxic from source, or making sure you trust whoever's repository you're using. The Tox project and Toxic developers have nothing to do with third party repos and we can't really help you in that regard.

**Comment by Sami32** [comment]
Ok, i guess that they was using that toxic version only:
https://build.merproject.org/package/repositories/home:nielnielsen/toxic

Thanks for your answer +1

**Comment by ghost** [comment]
Toxic -v 0.8.2 coming soon to openrepos.net Still on developments to get A/V work. Stay Tuned.

**Comment by ghost** [comment]
Thanks to @JFreegman for  your nice work on Toxic  =  )

**Comment by ghost** [comment]
@JFreegman  I am testing Toxic  v0.8.2, But I do not find how file transfer work. Can you explain me how this work ? I am ok on send the  file, but other person need accept this? 

Thanks

**Comment by JFreegman** [comment]
@Caballlero You use the `/sendfile` and `/accept` commands. Check the help menu.

**Comment by ghost** [comment]
Yeah  Look like I need to configure the toxic.conf to work more easier.
Yes I checked the help menu but I am new on toxic, I am having problem to undestand it. 
Thanks I will test if this work.

**Comment by Caballlero** [comment]
Mmm I checked the comand  /accept but this ask me for: Request ID requered. So what is this? 
Thanks

**Comment by ghost** [comment]
being more clear; I send the file with ~/Pictures/camera/sailfishOS.jpg (as example) then look like the file was send success, so the other side I do /accept ,then ask me for: > Request ID requered < So what is this?
Thanks

**Comment by JFreegman** [comment]
When you get a file transfer request it tells you an id associated with that request. So you type `/accept 0` or whatever the ID is.

Edit: The command is `/savefile` my mistake. When you get a file transfer you should see a message similar to this: `Type '/savefile 0' to accept the file transfer.`

**Comment by ghost** [comment]
thanks I am testing ....

**Comment by ghost** [comment]
Sorry @JFreegman  I had a bad build everything good now.
I want to translate toxic, is this possible?
T  h  a  n  k  s
