### ISSUE TITLE
Change color.

### ISSUE THREAD

**Issue by emkei-cz** [JFreegman/toxic#488]
Hi,

If I do not mistake, there is no easy setting to change the color (for example text)...
I have to change the color in the configuration files and then run the compilation.

Can you tell me which files contain the color code?
Thx.

**Comment by JFreegman** [comment]
There's no config options to change the colours, but you can mess around with the source if you want: https://github.com/JFreegman/toxic/blob/master/src/toxic.c#L236-L244
