### ISSUE TITLE
How to send a message to someone on the terminal interface?

### ISSUE THREAD

**Issue by ooof** [JFreegman/toxic#491]
How to send a message to someone on the terminal interface?

I checked the help file but I didn't find a way.

**Comment by soenkehahn** [comment]
Type `/add <TOX-ID>` and then wait until they confirm the friend request. Then hit `Ctrl-P` to switch to the `[contacts]` tab. Select the new entry, hit enter, type a message, hit enter.

It took me a while to figure this out myself just now. HTH.
