### ISSUE TITLE
Feature request: Aliases

### ISSUE THREAD

**Issue by fling-** [JFreegman/toxic#497]
Allow setting aliases / renaming buddies.
It is hard to distinguish between contacts without nickname set.
Also hard to find a contact when they are changing their nickname frequently.

**Comment by JFreegman** [comment]
Same answer that I gave here: https://github.com/JFreegman/toxic/issues/508#issuecomment-425173258

**Comment by JFreegman** [comment]
This is now possible and may be something I implement in the future.

**Comment by JFreegman** [comment]
This feature is in the latest release (0.15.0)
