### ISSUE TITLE
Re-colorizing history

### ISSUE THREAD

**Issue by moorchegue** [JFreegman/toxic#504]
It's lovely how toxic colorizes commands and messages. Now when you close and reopen a message window it'll display the history of your chat with that person (loading it from a log file I presume).

Would it be possible to additionally parse and re-colorize it so it would look the same or about the same? It would be very helpful for users who for one reason or another close their message windows or quit the app often to have that nice feeling of things reappearing just the way they've left them.

**Comment by JFreegman** [comment]
Unfortunately there is no easy way to do this, as the metadata used for colourizing isn't logged. It would be possible, but the entire logging implementation would need an overhaul.

**Comment by xeruf** [comment]
Why not heuristically recolorize the log? The format looks rather easy to colorize again, even `bat` generically colors the logfile ^^

**Comment by JFreegman** [comment]
Done. Will be in the next release.
