### ISSUE TITLE
Feature request: Autoaccept files

### ISSUE THREAD

**Issue by swiftgeek** [JFreegman/toxic#508]
Would be nice to have ability to auto-accept files, especially on per contact basis (including per user directory in addition to global default download dir)

qTox already has such feature since https://github.com/qTox/qTox/commit/43ac1dfd0dfb89fcdc2b410b9cbab2966ed75b15

**Comment by JFreegman** [comment]
This would first require implementing a save file for client-specific contact properties which is a pretty big undertaking. I would accept a pull request, but it's not a feature I'm planning on implementing myself right now.

**Comment by savchenko** [comment]
@JFreegman , would you consider implementing _"Automatically save all files under ~/foor/bar"_ option? :)

**Comment by JFreegman** [comment]
> @JFreegman , would you consider implementing _"Automatically save all files under ~/foor/bar"_ option? :)

This is already something you can do via the config. https://github.com/JFreegman/toxic/blob/master/misc/toxic.conf.example#L112

**Comment by parase4079** [comment]
bump

via the config does not auto accept files
is it possible to add printf or snprintf after
`line_info_add(self, false, NULL, NULL, SYS_MSG, 0, 0, "Type '/savefile %zu' to accept the file transfer.", ft->index);
`
like
`if (msg = File transfer queued) {
    snprintf("/savefile %zu");
    return;
}
`
as a result it should always auto accept incoming file transfer when online / away / busy
any quick fix, oneliner to add in chat.c here is ok for self build

**Comment by parase4079** [comment]
src/chat_commands.c
`void cmd_savefile(WINDOW *window, ToxWindow *self, Tox *m, int argc, char (*argv)[MAX_STR_SIZE])`
replace input via argv just with fixed var

**Comment by JFreegman** [comment]
This has been implemented via the `/autoaccept` command. In the future we may add a friend-specific setting for it, since toxic now supports that via the config file.
