### ISSUE TITLE
Some enhancements/bug-fixes to path handling behavior.

### ISSUE THREAD

**Issue by crabdancing** [JFreegman/toxic#510]
So, I was thinking of making some pull requests, but I wanted feedback first to see what y'all think.

### I think the file transfer feature could work a lot better if it...

* Didn't require quotes, as they seem logically unnecessary if there's no subsequent commands after you start typing the file name -- it can be safely assumed, as far as I can tell, that there are no commands delimited by spaces after the start of `/sendfile`.

* Could handle both single and double quotes. Some terminals will allow you to drag and drop files onto the terminal to insert a file path -- but do so with single quotes, because single quotes override the string literal parsing behavior of most shells. (e.g., `"/home/user/$monies.txt"` will be parsed as if `monies` was an environment variable, but the `$` will be ignored if you use `'` instead.

* Could expand `~`, without relying on autocomplete to explicitly expand it. I have many times typed `"~/stuff.txt"`, only to find toxic refusing to expand it. Now, I understand that some escape characters will probably be necessary if this is implemented, but it will need escape characters to support other special characters in file paths anyway -- and most terminal emulators, if they support drag and drop, should automatically include escape characters for any special POSIX characters -- so it *should* work seamlessly. Let me know if you foresee any problems I haven't thought of!

I also notice some bugs tab completion where toxic will assume that a file is a directory if it has no dot in its name -- which is hardly a safe assumption in many cases. It should actually read the file type and only add the `/` if it is indeed a directory.

Let me know what you think! :)

**Comment by JFreegman** [comment]
All good suggestions and I would be happy to review any pull requests you make. As for your first suggestion, I implemented that in the new_groupchats branch but never got around to merging it with master, so you could use that as a reference or just copy/paste it.

**Comment by crabdancing** [comment]
Oh, okies! ^.^ I'll get on that.

Speaking of un-merged code -- I was wondering about a cluster of commits to a forked repo by 'iphydf' -- which I tried compiling and seemed to work fine (although I'm not sure what they were changing as I haven't looked at them in super detail.)

Was there something wrong with those revisions, or did y'all just not have time to review them? If they're likely to be merged, should I base my fork off iphydf's code, or master?

**Comment by JFreegman** [comment]
We switched to iphydf's fork for active development. I do try to keep this one up to date but I've been slacking.

**Comment by crabdancing** [comment]
Ah, so that's beta and this is stable release. Fair enough!
