### ISSUE TITLE
Weird behavior in Terminology (clicking no longer works)

### ISSUE THREAD

**Issue by crabdancing** [JFreegman/toxic#511]
System information (via `uname -a`):
`Linux lithium 4.14.71-1-lts #1 SMP Thu Sep 20 20:14:07 CEST 2018 x86_64 GNU/Linux`
Relevant package information:
```
Name            : toxic
Version         : 0.8.2-3
Name            : terminology
Version         : 1.2.1-1
```

Okay, this is very odd, and I don't know where this bug should go -- whether it's a problem with Toxic or Terminology, or what could possibly be causing it. But I have been unable to recreate it in any other terminal program. Vim, Bash, ZSH, Weechat -- I have tested many nontrivial CLIs with fancy ncurses features, and they all seem to not cause the same thing.

Whenever I load Toxic through Terminology, clicking to select tabs no longer works, and right clicking stops working too. Key combos like Ctrl+Shift+T to create new tabs still work.

When I type `/quit` to exit, it starts working again.

This happens even when Toxic is running via Tmux. Any idea what could possibly be causing this, and how to debug it?

Edit 0:

The plot thickens. When I launch Toxic using `xfce4-terminal -e toxic`, right clicking and clicking on any of the menu bar options no longer works -- exactly the same symptoms that Terminology has. I originally suspected a problem with the EFL rendering system, but XFCE Terminal is a fairly run of the mill GTK app. And even weirder: with XFCE terminal, this only happens when I launch it via `-e` -- launching it normally, by typing `toxic` once ZSH is loaded, does not cause this problem.

Since two terminal emulators are doing it, I have to say that it's definitely a Toxic bug. I just can't imagine what on earth toxic could be doing to cause this. Any ideas?

Edit 1:

I ran `toxic -b` and piped `STDERR` to a file.  This is what I got:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  25 (X_SendEvent)
  Value in failed request:  0x0
  Serial number of failed request:  57
  Current serial number in output stream:  57
```

So, is toxic trying to intercept X mouse events? I wasn't even aware it was possible to steal events from a GTK menu bar, from inside a terminal program.

Edit 2:

I see no option to enable/disable mouse event capture, upon double checking `man toxic` and `man toxic.conf`. Whaaaat is happening?

**Comment by crabdancing** [comment]
After searching the issues a bit more, trying different search terms, I see that this issue has existed since 2014 and has still not been fixed? (#277)

Err... do y'all want a pull request to fix it? This seems like a very serious bug to me.

**Comment by crabdancing** [comment]
It should be noted that there is no mouse clicking that does anything in my install of Toxic.  Clicking tabs doesn't switch to them or anything. Has it been trying this whole time to intercept mouse events and silently failing?

Edit 0: the answer is yes. Yes it has. I get the same errors when looking at a non-glitching-out version of Toxic. I wonder how many people don't even notice that it's supposed to have mouse features, because they silently break on these systems and have no enable/disable option in `toxic.conf`.

In the short term, I think I should make pull requests to add and option in `toxic.conf` to disable these features so as to remove the need to recompile to disable X support (and, honestly, I think they should be disabled by default and labeled 'experimental' if they're as broken as they appear to be -- but who knows, maybe they work better than I think on some systems :stuck_out_tongue:).

In the long term, I'd be happy to help fix the X glitches so that this works properly and won't cause bizarre glitches! I need some C/C++ practice anyway.

What do y'all think?

**Comment by JFreegman** [comment]
> Okay, this is very odd, and I don't know where this bug should go -- whether it's a problem with Toxic or Terminology, or what could possibly be causing it. But I have been unable to recreate it in any other terminal program. Vim, Bash, ZSH, Weechat -- I have tested many nontrivial CLIs with fancy ncurses features, and they all seem to not cause the same thing.
> 
> Whenever I load Toxic through Terminology, clicking to select tabs no longer works, and right clicking stops working too. Key combos like Ctrl+Shift+T to create new tabs still work.
> 
> When I type /quit to exit, it starts working again.
> 
> This happens even when Toxic is running via Tmux. Any idea what could possibly be causing this, and how to debug it?
> 

If you want Toxic to work as intended I'd recommend gnome terminal or one of its variants. You could also try to compile it without X11 support. You're welcome to take a crack at fixing any terminal specific bugs you encounter as long as it maintains compatibility with other terminal emulators.

> It should be noted that there is no mouse clicking that does anything in my install of Toxic. Clicking tabs doesn't switch to them or anything. Has it been trying this whole time to intercept mouse events and silently failing?

The only thing mouse clicks should do in Toxic is highlight lines and open your terminal menu. It doesn't capture mouse events. There were plans to implement some mouse interaction, but the guy who added X11 support left the project and it was left a WIP.

**Comment by crabdancing** [comment]
@JFreegman So, uh... you don't want me to add an option to disable the `xtra.c` mouse support via `toxic.conf`?

I'm aware that custom compiling is an option -- I just think it's a bit unreasonable to expect everyone to custom compile it if they want to tweak one function (especially one that's a WIP and causes severe problems for some non-obscure well functioning terminal emulators).

Edit 0:
I mean, I looked at the code -- it seems pretty easy to add support for disabling that at runtime.

Edit 1:
I mean, if you don't want pull requests that's fine. I suppose I could just fork the whole thing and you can pull any of my changes back into the repo if they're good. Really, I just wanted to make it easy for the code to be merged if you like my changes is all. But it's up to you of course. ^.^

Edit 2:
I should note that fixing the bug will probably take me a long time, as I'm completely new to the codebase and will need some time to let it soak in and understand everything -- but adding an option to disable it via `toxic.conf` would be a lot faster and address the issue immediately for people who don't care about the X features and don't want to recompile on each update.

For that, all I'd need to do is find the entry points into the X-related code and check a bool variable set by `toxic.conf`. Now, I'm not super familiar with your conf parsing code, but it shouldn't take me too long to figure out how to add an option for that and have the code in `xtra.c` run conditional on that thingy being enabled...

Oh, and I do definitely think you should consider putting up a note in README.md, with "known issues" or something, warning people about the X features causing issues with some terminal emulators! It really threw me for a loop when I discovered that problem -- I've never seen a CLI application do something like that before.

**Comment by JFreegman** [comment]
An option to disable X11 would be fine, should be easy to implement. As for a known issues list, that already exists in the man page at the bottom, although it doesn't mention this particular one.

**Comment by crabdancing** [comment]
Okay, so I've been playing with the code a bit... does the X11 code actually *do* anything besides the sound and display notifications? It seems like that's all it does... 

I think I should implement a different method for display/sound notifications. I am tempted to actually do it via a hook that gets called when a message is received, then runs `notify-send`, `aplay` or whatever the user wants... hell, if the user wants to make sure she's awoken when she receives a message, she can make a robot that pours coffee on her head every time she receives one. Which is great for hackability -- and is why I'm _very_ partial to this sort of solution.

And it'd would help to make the core code more minimal, but it'd also increase the number of dependencies if you wanted to avoid the broken X11 code...

Ideally, whatever method I used would be portable for multiple platforms, and lightweight, and not increase dependencies... but I suppose those are conflicting goals. I'm not quite sure which to prioritize.

It's notable I've quite often had problems with the sound code in Toxic anyway -- it tries to go through ALSA instead of Pulseaudio, and since I use a bluetooth headset, this means it's obligated to occasionally send audio to the wrong sink and make a mess of things until the application is restarted. So, I suppose having a different sound method would also implicitly fix that...

**Comment by crabdancing** [comment]
I suppose a hook feature just for receiving messages is unnecessary if the user is willing to enable logging -- one could simply have a tail-like application follow the log, assuming it's not cached to memory and dumped all at once...

*/me has not yet read the logging code*

But then, some might not like that, considering how privacy focused tox users are. And it might be difficult and hacky to make something that runs reliably like that. I can't think of any program that functions like that besides fail2ban, and fail2ban is very specialized and wouldn't be very suited to triggering arbitrary actions AFAIK.

Anyway... I'm just trying to imagine as many use cases as possible and accommodate them to save on the amount of base code that might be needed in the future. And kind of overwhelming myself in the process, per usual... :stuck_out_tongue:

**Comment by crabdancing** [comment]
Damn. I don't even know how `alut` works. That seems to be what you're using for sound. I don't see how that's breaking when the X11 code is disabled...

**Comment by crabdancing** [comment]
It SAYS on the website that it supports pulseaudio as a backend... so there may be more than one thing broken here...

I don't like the idea of changing code dependencies in a project this large. I need to figure out what's going on here.

_stay tuned for more drunk coding_

**Comment by crabdancing** [comment]
I think I'm just going to have to give up and start commenting everything so I can follow where all the entry points are. I hope y'all aren't too annoyed by them when they show up in my pull requests.

**Comment by crabdancing** [comment]
Yup. I'm just going to need to comment every single thing in xtra.c, as soon as I figure out exactly what it's doing, which will probably require looking up a bunch of functions since I have no familiarity with Xlib or Xatom or any of these things.

On a side note, what do the project devs use to write this code? Can you recommend a good flying-by-the-seat-of-your-pants, tells-you-slash-reminds-you-what-functions-do IDE? I'm not entirely sure Vim/Gedit/Geany will cut it, and Code::Blocks is crashing on my machine for reasons of Arch Linux.

Edit 0: I just realized I've been posting new comments for every thought I have instead of appending them to the same post, which means you're probably getting spammed with email notifications for every single comment. :disappointed: Sorry about that!

**Comment by JFreegman** [comment]
> Okay, so I've been playing with the code a bit... does the X11 code actually do anything besides the sound and display notifications? It seems like that's all it does...
> 
> I think I should implement a different method for display/sound notifications. I am tempted to actually do it via a hook that gets called when a message is received, then runs notify-send, aplay or whatever the user wants... hell, if the user wants to make sure she's awoken when she receives a message, she can make a robot that pours coffee on her head every time she receives one. Which is great for hackability -- and is why I'm very partial to this sort of solution.

X11 is used to tell us whether the window running toxic is focused or not. We ideally only want notifications when the window is not focused.

>Damn. I don't even know how alut works. That seems to be what you're using for sound. I don't see how that's breaking when the X11 code is disabled...

It shouldn't. To disable X11 without re-compiling you just need to add a boolean param to the `init_xtra()` function which would exit the function immediately. The boolean value would be supplied by the user_settings struct (see `settings.c/h`). You shouldn't need to worry about how the internals of xtra.c work. All subsequent calls to anything in xtra.c should fail silently (though this isn't exactly best practice it will work).

> On a side note, what do the project devs use to write this code? Can you recommend a good flying-by-the-seat-of-your-pants, tells-you-slash-reminds-you-what-functions-do IDE? I'm not entirely sure Vim/Gedit/Geany will cut it, and Code::Blocks is crashing on my machine for reasons of Arch Linux.

Personally I keep it simple with Sublime Text and a terminal or two.

Edit: It should be noted that X11 is also used for video calls, which is entirely separate from everything in xtra.c. So what you're doing is not actually disabling X11, but a subset of its functionality.

**Comment by crabdancing** [comment]
Aaaah, okay! That helps. What if I just check a boolean value in the place where init_xtra() is called, and skip the whole function call to begin with? Is it still needed for something else?

**Comment by JFreegman** [comment]
> Aaaah, okay! That helps. What if I just check a boolean value in the place where init_xtra() is called, and skip the whole function call to begin with? Is it still needed for something else?

Since the init function should only ever be called in one place it should be effectively the same. Just a matter of taste.

**Comment by JFreegman** [comment]
This unfinished feature has been removed from Toxic.
