### ISSUE TITLE
Do not write profile data to disk every AUTOSAVE_FREQ seconds

### ISSUE THREAD

**Issue by mrkiko** [JFreegman/toxic#514]
It would be useful if we could get toxic to not write it's profile data
every AUTOSAVE_FREQ by default.
This would be useful especially on situations where writing to the media
isn't cheap in terms of media lifetime.
Thank you for all your work, and all you've done guys.

Enrico

**Comment by JFreegman** [comment]
It would be fairly easy to make this a config setting. I'll look into it
