### ISSUE TITLE
Toxic can't write config file

### ISSUE THREAD

**Issue by simwin** [JFreegman/toxic#518]
Toxic can't create and save config file toxic.conf
v.0.8.3
OS - Linux Mint
Please check it.

**Comment by JFreegman** [comment]
I can't tell much without an error code. Does Toxic have write permissions for your config directory?

**Comment by simwin** [comment]
Yes, Toxic has permissions and there isn't error code at all.

**Comment by simwin** [comment]
Ok. I've compiled toxic by myself and now it works fine. Thanks!
