### ISSUE TITLE
since recent commit: sendfile does not accept filenames  with too many spaces or non-ascii letters

### ISSUE THREAD

**Issue by ant11** [JFreegman/toxic#522]
Since version 0.8.3 with its commits 
 * 56e03a3f8b4fc690601bdd5ec8884b84d09bce7c and
 * b6c746b5f54dc4fbe154d070f8a066ce0ab3b54a
I cannot enter filenames with more than one space, too long or have one or more non-english letter or only numbers in their name. If I enter the correct name manually, it cannot find the file - if I try it with autocompletion it does not find any file with that naming conditions.

**Comment by JFreegman** [comment]
>I cannot enter filenames with more than one space [...] or more non-english letter or only numbers in their name

I just tested all three of these cases and they seem to be working fine. You aren't testing with a 0 byte file are you? As far as length goes, toxic uses the posix standard `PATH_MAX`.

**Comment by ant11** [comment]
The files are > 0 byte. I checked and in my shell I have no PATH_MAX set. What is then the default PATH_MAX in toxic?

**Comment by JFreegman** [comment]
PATH_MAX is defined as 4096 in limits.h. Can you give me more info about your system?

**Comment by ant11** [comment]
My system is a Gentoo and zsh (utf8)

Here is one error case:
e.g. I have this two paths/files on my system:
```
 /home/user1/fremdaj datenoj/Lala Fasel
 /home/user1/fremdaj datenoj/LalaFasel
```
(first with a space, second not)
Then it is _imposssible_ to send the first file as I cannot enter the second space after `Lala`. A normal space is not working nor a backlash-space; I only can enter the second file.

**Comment by JFreegman** [comment]
I see the issue now. Tab complete won't complete a path with a space in it if you hit tab after a space. This is unrelated to file transfers as you can still type the paths manually and it will work fine. I created a pull request for a fix here https://github.com/TokTok/toxic/pull/39
