### ISSUE TITLE
I want to post my project,my code and everything I tried for.Someone please suggest .

### ISSUE THREAD

**Issue by blprasad** [JFreegman/toxic#525]
Hi all ,I worked for several days on a project ,I don't know if this is a right place for asking a suggestion?Now I want to post all my work ,here or somewhere .I want it to make it available to everyone who could make use of it.I planned for a startup with my work ,but now unfortunately I cannot proceed with my actual plan because I got sick.I don't want my effort to go useless. 

I am very new to posting a project online.Please suggest the risks and things involved in how to.
The project is based on toxic,  toxic client that runs on a orange pi zero board.User can enter data using a 4x4 matrix keypad and view contacts on monochrome lcd ,and add contacts and make calls.no video call support only basic calling is possible.My effort is very little if I compare with that of yours.Earlier I thought with selfish goals but not anymore.I want to donate my work to   community.If someone uses it for own or educational purpose.

thanks

**Comment by JFreegman** [comment]
Sounds like an interesting project. All you have to do to share it with the community is [create your own](https://help.github.com/en/articles/create-a-repo) public github repo.

**Comment by blprasad** [comment]
I finding difficulty in uploading my files created a private github repo ,will make it public when every thing is uploaded properly.

**Comment by blprasad** [comment]
now its uploaded properly, preparing Readme files now ,soon I will upload them too.
