### ISSUE TITLE
PTT mode?

### ISSUE THREAD

**Issue by janekska** [JFreegman/toxic#531]
Hi,

Could it be possible to make voice calls like in two way radios with Push To Talk (PTT) button?

I.e, call for a group is auto answered as somebody in the group uses PTT function and hangs when PTT function is stopped (f.ex.. release a button on keyboard). Also probably with Busy Channel Lockout (BCL) function - if there is an active call in a group then others can't use PTT.

brgds

**Comment by JFreegman** [comment]
> I.e, call for a group is auto answered as somebody in the group uses PTT function and hangs when PTT function is stopped (f.ex.. release a button on keyboard). Also probably with Busy Channel Lockout (BCL) function - if there is an active call in a group then others can't use PTT.

This would be a bit difficult and require core changes, although it is possible. However, it wouldn't be practical start a call and hang up every time someone pushes the talk button. It would make more sense to leave the call ongoing as per the current group audio behaviour. In that case, the only modification you would need is for the client to detect when someone else is talking and to be able to block input.

**Comment by janekska** [comment]
Thank you for your replay!

Did I understood right, that you see two ways:
- my idea (proposed workflow) realization is possible, but would be rather complicated,
- your proposal to leave call ongoing
?

If yes:
 - are there any network traffic / processor time  on silence,
- what programming knowledge would I need to do that
?

The idea is to use a Tox client (Toxic?) as two way radio gateway.
F.ex. put it on Raspbery Pi and with some hardware connect it to radio.
Your second proposal is even better for such setup, because then I would not need any voice activation features from radio to PC. I.e I can then use any two way radio with VOX with some very simple hardware.

**Comment by JFreegman** [comment]
> my idea (proposed workflow) realization is possible, but would be rather complicated,
> your proposal to leave call ongoing

Right.

> are there any network traffic / processor time on silence

There shouldn't be in theory but I'm not entirely sure.

> what programming knowledge would I need to do that

It's hard to say. Toxic doesn't have group audio implemented in the first place. If you can manage that, then everything else should be easy.

**Comment by janekska** [comment]
May be start with https://github.com/hqwrong/minitox ?

**Comment by JFreegman** [comment]
It would be easiest to start with a client that already has group audio implemented (i.e. utox or qtox), but if you need something minimalist then toxic or minitox would be a better choice. Even a standalone client specifically made for the task could be a consideration.

**Comment by janekska** [comment]
Thank you for your answers!
