### ISSUE TITLE
/video not working on arch linux

### ISSUE THREAD

**Issue by dkwo** [JFreegman/toxic#538]
On Arch Linux, if I try to set video by
/svdev in 0
which corresponds to /dev/video0, my laptop webcam, then during a cal /video does not work: it crashes my contact's toxic, and on my side only a black 'video receiver' window opens up.
Am I missing something?
Btw, is there a way to e.g. use mpv for handling video?

Thanks.

**Comment by JFreegman** [comment]
It would be very helpful to see a stack trace of the crash. Are you able to reproduce this bug locally with two instances of Toxic?

**Comment by TheChymera** [comment]
@JFreegman I think I might have come across a similar issue (on Gentoo). How can I provide a stack trace?

**Comment by JFreegman** [comment]
> @JFreegman I think I might have come across a similar issue (on Gentoo). How can I provide a stack trace?

Assuming you compiled with -o0 and/or debug flags:

1. Run two toxics
2. Run gdb and attach the toxic process you intend to crash: `attach [pid]` (might need admin privilegs)
3. Crash toxic
4. In gdb type `backtrace full`

**Comment by dkwo** [comment]
i haven't been using this (hence reproducing the issue) for a while, so i'm closing this. feel free to reopen if still relevant.
