### ISSUE TITLE
Asterisk key on numpad displays 'Oj' (without quotes) instead of '*'

### ISSUE THREAD

**Issue by danmanrana** [JFreegman/toxic#541]
Is there a change I need to make a config or is this supposed to work out of the box? The '/' numpad key produces 'Oo', '-' 'Om', '+' 'Ok', and '.' doesn't display. It works if I turn numlock on though.

**Comment by JFreegman** [comment]
That's just how ncurses interprets key strokes by default.

**Comment by danmanrana** [comment]
Ok, but if others become confused about the same thing, maybe there could be a short text to explain that, including an option to change that default, if possible?

**Comment by JFreegman** [comment]
> Ok, but if others become confused about the same thing, maybe there could be a short text to explain that, including an option to change that default, if possible?

This is standard num pad behaviour. If num lock is off then the secondary key mappings are used (e.g. on my keyboard the `.` key maps to `del`). I've never had anyone complain about it before.

**Comment by danmanrana** [comment]
Is that a uniquely Ncurses thing? Because if my numlock's off, the keys still display normally on Firefox and Bash.

**Comment by JFreegman** [comment]
> Is that a uniquely Ncurses thing? Because if my numlock's off, the keys still display normally on Firefox and Bash.

I would say your setup is abnormal. How do you use the secondary mappings for your num pad in Firefox and your terminal emulator? For example, you should be able to use the arrow keys to scroll through your history or move the cursor left and right (toxic should behave the same way).

**Comment by danmanrana** [comment]
The only key I sometimes use on my numpad is the * regardless of whether or not numlock's on. Arrow keys work fine on e.g. Reddit. I do remember that I copied the keybind part of sample Toxic config file on the Github page because I couldn't figure out how to change tabs (first time using Toxic) and thought I needed to copy & paste it in.
