### ISSUE TITLE
Detaching tmux causes program to quit

### ISSUE THREAD

**Issue by 3291823** [JFreegman/toxic#546]
Toxic version 0.8.3
Toxcore version 0.2.12
I have the same problem as #397 does, detaching causes toxic to quit. I must then `reset` or reopen a tmux buffer to rerun toxic.  St terminal.

`X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x2000006
  Serial number of failed request:  35
  Current serial number in output stream:  35
`
TIA.

**Comment by JFreegman** [comment]
Can you tell me your OS/distro, terminal emulator, and tmux version? Also can you try to recompile without x11 using the `DISABLE_X11=1` make option and see if it still happens?

**Comment by 3291823** [comment]
Voidlinux, fully updated.
tmux 3.1b
st 0.8.2

Attempting to compile toxic results in an error which I cannot seem to solve. I have toxcore, toxcore-devel, toxcore-dbg installed, yet the make script still complains. Perhaps I could form a symlink somewhere?

This is a list of toxcore-devel files on my system.
/usr/include/tox/tox.h
/usr/include/tox/toxav.h
/usr/include/tox/toxencryptsave.h
/usr/lib/libtoxcore.a
/usr/lib/pkgconfig/toxcore.pc
/usr/lib/libtoxcore.so -> /usr/lib/libtoxcore.so.2

**Comment by JFreegman** [comment]
> Attempting to compile toxic results in an error which I cannot seem to solve. I have toxcore, toxcore-devel, toxcore-dbg installed, yet the make script still complains. Perhaps I could form a symlink somewhere?

What's the error? Are you sure you have all of the core dependencies listed in Toxic's install instructions?

Edit: It would also be a good idea to see if the bug persists in a different terminal emulator so we can rule that out.

**Comment by 3291823** [comment]
The bug appears to be `St` specific. Will close the issue for now.
