### ISSUE TITLE
Messages not delivered when you close pane

### ISSUE THREAD

**Issue by adscadscfr** [JFreegman/toxic#559]
To reproduce:
- start a chat with a friend
- wait for them to go offline
- type a message
- see the red X appearing beside the message
- /close the chat window

When your friend reappears, the message will *not* be delivered (it would have been if you had left the chat-window open).

**Comment by JFreegman** [comment]
This isn't a bug, just a limitation of offline message sending.

**Comment by danmanrana** [comment]
The Tox protocol is peer-to-peer so both users need to be online for messages to be transferred. A way around it is to have another device (doesn't need fancy specs) act as an always-or-most-of-the-day on server to always be able to receive messages and you use it via SSH.

**Comment by adscadscfr** [comment]
I think I have not explained by problem clearly enough.

I am aware that both users need to be online for a message to be delivered!
What I think it is not ok is the difference in behaviour:
- if you let the "chat pane" (I am not talking about toxic itself, just the pane) open, once your friend pops online the chat message will be delivered
- If you close the "chat pane" (with /close) the message will be discarded, so even if your friends returns online, the message will not be sent.

Obviously toxic tries to deliver the message in one case but gives up in the other. I believe a uniform behaviour would be better.
Did I meanage to clarify what I meant?

**Comment by JFreegman** [comment]
I understood what you meant. Like I said, that's just a limitation of the client. When you close a chat window all the associated buffers are cleared. To properly fix this would require some structural changes and an additional config file that saves unsent messages when you exit the client. The only solution for now is to just not close a window before your message is delivered.
