### ISSUE TITLE
Extend list of the allowed colours

### ISSUE THREAD

**Issue by savchenko** [JFreegman/toxic#560]
Toxic currently accepts:

> black, white, red, green, blue, cyan, yellow, magenta

Which is missing grey as well as any of the "bright" colours.
Any chance to support at least 16-colour palette?
![image](https://user-images.githubusercontent.com/300146/107186450-3aaa1200-6a34-11eb-8603-fa576aae3c5a.png)
This would already allow some theming. Being able to access the whole set of 256 colours is even better.

**Comment by clort81** [comment]
Note that ncurses makes all this color stuff royally gimped, since it has to support ancient serial terminal protocols.  The curses system offers a limited 'palette' of 'color pairs', not arbitrary FG/BG setting.

Much simpler to just emit ANSI formatting codes directly and skip the ncurses middleman.

Why people still think ncurses makes sense for text-ui clients nowadays is beyond me.

**Comment by GaKu999** [comment]
Also maybe a "default" color that just uses the terminal default foreground/background, since I have transparency, black is just a non-transparent bar, contrary to the rest of it.

**Comment by JFreegman** [comment]
> Also maybe a "default" color that just uses the terminal default foreground/background, since I have transparency, black is just a non-transparent bar, contrary to the rest of it.

You can set  `native_colors=1` in the UI section of the toxic configuration file. See the `toxic.conf.example` file or use `man toxic.conf` if you're not sure how to do that.

**Comment by GaKu999** [comment]
I have native colors, it uses the terminal native color for black, but black is not transparent. ;)

**Comment by JFreegman** [comment]
> I have native colors, it uses the terminal native color for black, but black is not transparent. ;)

I see. I'm not entirely sure if that's possible to do with ncurses.

**Comment by GaKu999** [comment]
Just don't set the background color. :)

**Comment by GaKu999** [comment]
Like for example, all of the text that toxic prints in a conversation, it gets foreground colors and such, but it doesn't set the background color, so, it defaults to the terminal default. But since toxic always sets the background for the top and bottom bar, it will never be transparent.

**Comment by GaKu999** [comment]
In other words, default here would be a noop code-wise, disabling colors as well would be the same as having all of them (foreground and background) as default, since in the end, toxic would just noop on coloring and just print as is.

**Comment by JFreegman** [comment]
So your issue is that the top and bottom bars aren't transparent with the rest of the background? Changing them to default would would effectively break the UI, particularly for those who don't have transparent terminals. I think the solid bars are something you'll have to live with.

**Comment by GaKu999** [comment]
Err, no, why would no coloring break the terminal?

**Comment by JFreegman** [comment]
> Err, no, why would no coloring break the terminal?

I mean it would break the UI design.

**Comment by GaKu999** [comment]
But that is why its configurable no? And it defaults to a cyan no?

**Comment by JFreegman** [comment]
So you're suggesting an option to set just the bar colours to default terminal colours? I'll look into that when I have the time

**Comment by GaKu999** [comment]
More like, an option for coloring that does nothing, since nothing equals to the default colors.

**Comment by GaKu999** [comment]
Similar in nature to vim's color identifier NONE/none.

**Comment by JFreegman** [comment]
We've extended the list of colours to include pink, brown, gray and orange as config options. However, these non-standard colours are interpreted differently depending on your terminal emulator/terminfo, and therefore don't work in some terminal emulators. For this reason, toxic will likely never use non-standard colours in its default config.
