### ISSUE TITLE
implement ability to change contact nick

### ISSUE THREAD

**Issue by sss123next** [JFreegman/toxic#565]
it's often convenient to set custom contact nickname (locally)

**Comment by JFreegman** [comment]
This has been discussed many times before. In order to set custom contact info toxic would require a second data file. This is a lot of work for little reward, so I've opted not to implement it.

**Comment by sss123next** [comment]
reward is not so little, but ok, i got it.

**Comment by JFreegman** [comment]
This is now possible and may be implemented in the near future.

**Comment by JFreegman** [comment]
Done https://github.com/JFreegman/toxic/commit/6dc22b519c31512c970dcf2afb91976bf5e5a73e
Will be in the next release.
