### ISSUE TITLE
Notification Daemon Recconect

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#571]
If restart notification-daemon or kill and start again, we not see new notification 
dbus-monitor see log notification but not show notification in desktop.
need only restart toxic client for notification work.

## Step
1. Start Notification-daemon
1. Start Toxic
2. Stop notification-damon
3. Start again notification-daemon
4. send test message

that is, if the user reboots the notification daemon, then new messages will not be displayed
(works fine with other applications) 

```
dunst 1.5.0
notification-daemon 3.20.0
notify-osd 0.9.35

Toxic version 0.10.1
Toxcore version 0.2.12
```

**Comment by JFreegman** [comment]
The solution here seems to be to restart toxic after you restart your notification daemon.
