### ISSUE TITLE
Feature Request: Inscreen Notification of incoming Message

### ISSUE THREAD

**Issue by clort81** [JFreegman/toxic#574]
Running toxic for a few months now - I miss all incoming conversations.

When in a chat window with a person, chat goes idle - another person messages me and I do not get notified that an incoming new message was received.

I suggest a new feature: to display the chatter sending new message in red text in some free space on status bar, and provide a keybinding for the user to quick-switch to the window with the incoming chat (or filetransfer).

**Comment by JFreegman** [comment]
I'm not exactly sure that I understand the problem you're having. When you have toxic open and receive a new message, a new tab coloured cyan will open in the bottom status bar, with a number indicating how many unread messages you have. If toxic is minimized, you will receive a sound/desktop notification (assuming you enabled those features at compile time).

**Comment by JFreegman** [comment]
Closing stale issue with no further correspondence
