### ISSUE TITLE
Status always "Away from keyboard, be back soon!"

### ISSUE THREAD

**Issue by clort81** [JFreegman/toxic#581]
If i type /status online or /status online "i am really online"
i receive
```
Your status has been changed to online.
```
but other clients see 
 "Away from keyboard, be back soon!"

Built git master 2021-08-13 on devuan aarch64.  gcc 10.2.1-6

**Comment by JFreegman** [comment]
When you detach/re-attach a tmux or screen instance your status and note will be automatically changed. I'd guess that when you're checking on your other client, you're doing something to trigger that auto-away feature. You can disable that feature in toxic's config if you want.

Adding the additional note to the `/status` command should have no effect, as this feature was removed a while ago. I forgot to remove that from the help dialog. To change your note, use the `/note` command.

**Comment by JFreegman** [comment]
Closing stale issue with no further correspondence
