### ISSUE TITLE
Feature Request: Disable beeps for friends who bounce off and on.

### ISSUE THREAD

**Issue by clort81** [JFreegman/toxic#582]
Several contacts have a problem where they bounce off and on the network.

This causes constant repeated beeping.

Request a toggle to disable audio notifications for specific contacts.

**Comment by JFreegman** [comment]
This would require an additional save file for per-contact config options, which is something I've decided against doing for the time being.

**Comment by JFreegman** [comment]
Implemented https://github.com/JFreegman/toxic/commit/2a5bcfb482050ff78e02031634c5e867ad5c5e53
