### ISSUE TITLE
How is the python feature used?

### ISSUE THREAD

**Issue by emdee-is** [JFreegman/toxic#621]
```cfg/checks/python.mk``` seems to build the python feature by default.

```
Variables for Python scripting support
```

But there is no documentation on  how the python feature is used.

**Comment by emdee-is** [comment]
JF replied in chat
>  the guy who implemented that disappeared  before writing docs for 

so maybe a user who uses it can help out here with a simple description.

**Comment by aavina** [comment]
Here's the git blame for that file which points out it was added 6 years ago. It may give more clarity to how it was intended to be used and make docs against.

https://github.com/JFreegman/toxic/blame/master/cfg/checks/python.mk

**Comment by emdee-is** [comment]
@aavina Thanks that was very helpful and I didn't know how to use that

@JFreegman 
> the guy who implemented that disappeared before writing docs 

That's not so: in the commit @aavina dug up, there's lots of documentation, done to the highest Python standards with sphinx, and including examples.
https://github.com/JFreegman/toxic/commit/b3ed8bc35c6716b4828415ef65e54d89101a9a37#diff-6495ad0f9eba70f9005beef7d609ae2ae5fdddc7de8d78215388bf3f33acae06

Could you include the documentation files  into toxic so we can see how to use it. It might be a viable plugin system for toxic.

**Comment by emdee-is** [comment]
Never mind - it's in the source in the apidoc directory - my fault.
