### ISSUE TITLE
feature suggestion: search through scrollback

### ISSUE THREAD

**Issue by emdee-is** [JFreegman/toxic#623]
I find myself looking back in the scrollback for something specific.  What I'd like to do is go to the top and type ^S or ^F and incrementally search for a word, terminating when I hit <CR>.

Just a "nice to have".

**Comment by JFreegman** [comment]
After thinking on this a while I think it'd just be reinventing the wheel. With commit https://github.com/JFreegman/toxic/commit/d38a73e5365eccbc40cf0f77321e584ef7b4178f you can now easily do this via a different tool such as grep or a text editor of your choice. Will re-explore the idea if chatlogs ever become encrypted.
