### ISSUE TITLE
Why is toxic connecting to 127.0.0.1:23075 a 1000 times an hour?

### ISSUE THREAD

**Issue by emdee-is** [JFreegman/toxic#628]
Why is toxic connecting to 127.0.0.1:23075 
```
D 2022-10-08 16:57:24.214806 network.c:1748(net_connect) - connecting socket 26 to 127.0.0.1:23075
```
5229 times in 4 hours.

There are no matches for: 23075 in the code or   in ``` tox/*json``` - it's no port I've ever used

Toxic is started with  ```-b -4 -L```

It can't help efficiency.

**Comment by JFreegman** [comment]
This issue belongs in the c-toxcore repo as it's not a client/UI issue.

**Comment by emdee-is** [comment]
Turns out it was a logging issue with 23075 being a logging error dues wrong-endianness.
