### ISSUE TITLE
"Consider helping the Tox network by running toxic with -T, --tcp-relay"

### ISSUE THREAD

**Issue by emdee-is** [JFreegman/toxic#631]
On the Home page you give some useful info on settings.

How about adding an advertisement:

"Consider helping the Tox network by running toxic with -T, --tcp-relay"

If each non-Tor user was a tcp_server it would help resilience in places like Iran.

**Comment by JFreegman** [comment]
TCP servers generally use enough bandwidth to warrant being run on a dedicated machine, as they're continually relaying high bandwidth communications such as file transfers and A/V streams. It's probably not something you'd want to run on your desktop under normal circumstances. The option is just there in case someone wants it.

**Comment by emdee-is** [comment]
Of course, I forgot about the AV. Still it may be worth asking users to help do something about the ease of blocking such a limited number of BS nodes. Tor put likes line "consider helping by running a relay" in their documentation and it helped a bit, *and* they are too varied to be able to easily block. I'm trying this out with toxic and toxygen to try running Tox *in* Tor,

I'll close the issue as "food for thought".
