### ISSUE TITLE
Topic bar

### ISSUE THREAD

**Issue by Zer0-One** [JFreegman/toxic#638]
Toxic should have a bar at the top of the window that displays the topic for the currently open chat. Currently, the topic is only displayed on first join, or when the /topic command is given.

**Comment by Pigpog** [comment]
Agreed, this is an important feature of group chats that's not given enough visibility on Toxic. 
Same applies to conference chat titles.

**Comment by JFreegman** [comment]
Done https://github.com/TokTok/toxic/pull/313
