### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by CraftedCat** [JFreegman/toxic#639]
Hi, 
[undefined symbol: tox_callback_group_invite](toxic: symbol lookup error: toxic: undefined symbol: tox_callback_group_invite)

Toxic version 0.11.3_r2118
Toxcore version 0.2.18

**Comment by Pigpog** [comment]
Your build of Toxic is trying to use new features that aren't available in your version of Toxcore.
Are you using a package manager to install Toxic, or do you compile it yourself?

**Comment by Green-Sky** [comment]
> Toxcore version 0.2.18

the new toxic requires features currently only found in toxcore master. so until a new toxcore release is made, you will have to rely on the static build or compile toxcore yourself :)

**Comment by JFreegman** [comment]
> > Toxcore version 0.2.18
> 
> the new toxic requires features currently only found in toxcore master. so until a new toxcore release is made, you will have to rely on the static build or compile toxcore yourself :)

Or do `git checkout v0.11.3`
