### ISSUE TITLE
Page-Up/Page-Down should page up and down

### ISSUE THREAD

**Issue by Zer0-One** [JFreegman/toxic#640]
Page-Up/Down should move the chat window up/down by 1 page instead of 1 line.

**Comment by JFreegman** [comment]
You can customize this in the [keys](https://github.com/JFreegman/toxic/blob/master/misc/toxic.conf.example#L147) section of Toxic's config file

**Comment by Zer0-One** [comment]
The default should be changed.

**Comment by JFreegman** [comment]
https://github.com/TokTok/toxic/pull/312
