### ISSUE TITLE
tox.chat is distributing toxic with CVE vulnerabilities

### ISSUE THREAD

**Issue by emdee-is** [JFreegman/toxic#648]
tox.chat - the flag portal for tox - is distributing a version of toxic with a known CVE
github.com/Jfreegman/toxic/releases/download/v0.12.0/toxic-minimal-static-musl_linux_x86-64.tar.xz

Who can update tox.chat?

**Comment by JFreegman** [comment]
That's the latest version of Toxic. What CVE are you referring to?

**Comment by JFreegman** [comment]
There is no patch for that issue although I believe someone has recently renewed work on it. Moreover this is not a client issue.
