### ISSUE TITLE
0.13.1 fails to build against `toxcore` master: `groupchats.c: error: too many arguments to function ‘tox_group_send_message’`

### ISSUE THREAD

**Issue by barracuda156** [JFreegman/toxic#656]
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_toxic/toxic/work/toxic-0.13.1/src/groupchats.c: In function ‘send_group_message’:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_toxic/toxic/work/toxic-0.13.1/src/groupchats.c:1560: error: too many arguments to function ‘tox_group_send_message’
make: *** [/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_toxic/toxic/work/toxic-0.13.1/build/groupchats.o] Error 1
make: *** Waiting for unfinished jobs....
  CC    help.o
```
It does build against an older version (2023.11.18 works, 2024.01.06 does not).

**Comment by JFreegman** [comment]
Unfortunately someone made an API breaking change to toxcore master while I was away on vacation. Try building against toktok/c-toxcore commit 6c6c0b1. You can also build toxic Jfreegman/master against toktok/c-toxcore master.

**Comment by barracuda156** [comment]
Got it, thank you for clarifying. Since it builds fine with existing version of `toxcore` in Macports, I will just update `toxic` now, and once there is a new release, will update both ports.
