### ISSUE TITLE
DNS leak?

### ISSUE THREAD

**Issue by sh3ll4rpw** [JFreegman/toxic#663]
Toxic use the toxDNS and leaks DNS? Or this issue has been fixed?

**Comment by JFreegman** [comment]
Toxic has ToxDNS implemented but there are no servers running it at the moment so it's a stale feature. I'm not sure what you mean about DNS leak, as Toxic does not hide your IP address by default regardless. If you're using Toxic over a proxy then the DNS requests will be done through the proxy and no leakage will occur.

**Comment by sh3ll4rpw** [comment]
I'm using a tor proxy. You're sure there are no IP and DNS leaks? Connection is fully forced through the selected proxy?

**Comment by JFreegman** [comment]
I can be sure of nothing, but it is designed not to leak your IP address through DNS or otherwise, assuming your proxy is set up correctly and you are not running Toxic with UDP enabled.
