### ISSUE TITLE
Toxic group chat does not seem to be working

### ISSUE THREAD

**Issue by end-of-line90** [JFreegman/toxic#664]
I tried using toxic and I noticed that while direct chat seems to be working, group chat doesn't seem to be working at all.

I get always connecting status even though I try to set the group chat with two users on 2 different accounts of the same host

toxic
```
commit e399f3fc75a7cf8c8369e939db79fd442ae79d1a (HEAD -master, origin/master, origin/HEAD)
Author: jfreegman <jfreegman@gmail.com>
Date:   Mon Jun 24 08:43:13 2024 -0400

   fix: race condition when drawing group/conference peer list

   The number of peers can change between and within iterations leading to
   an out of bounds index. Now we just lock the entire loop, which is less
   efficient but necessary.
```
c-toxcore https://github.com/TokTok/c-toxcore
```
commit 102a1fa9b82a32274ab86583f3716139ba92295c (HEAD -> master, origin/master, origin/HEAD)
Author: Maxim Biro <nurupo.contributions@gmail.com>
Date:   Sat Apr 27 12:15:40 2024 -0400

    chore: Fix -Werror=maybe-uninitialized in a test
```

Any ideas what I could have done incorrectly?

when /join ${chatId}
> Failed to join group (error 2)

On the side of who created the group chat
![image](https://github.com/JFreegman/toxic/assets/65855254/b59d1adb-af38-455c-b230-b808696e0d5d)

On the side of joining the group chat
![image](https://github.com/JFreegman/toxic/assets/65855254/c2dc0295-636a-471f-b5f6-0d3878e625ff)

**Comment by JFreegman** [comment]
This is most likely due to the fact that the network is still majority (60-70%) not using an up-to-date toxcore. If you leave it running it will connect eventually, but it might take a long time. Sometimes, minutes, sometimes hours. You can still invite your friends directly using the `/ginivite` command though.

**Comment by end-of-line90** [comment]
> If you leave it running it will connect eventually, but it might take a long time. Sometimes, minutes, sometimes hours. You can still invite your friends directly using the `/ginivite` command though.

Many thanks for suggestion. I'll check this out - I'll close the issue for now
