### ISSUE TITLE
unable to switch to Contacts

### ISSUE THREAD

**Issue by hxm-cpp** [JFreegman/toxic#666]
![WindowsTerminal_TMcGtG4vO0](https://github.com/user-attachments/assets/9b98175f-c44d-4ef6-818e-0e91b8f3c96e)

**Comment by JFreegman** [comment]
Did you try `ctrl+p` and `ctrl+o`?

**Comment by hxm-cpp** [comment]
the problem was on the windows new garbage cmd. works well on git bash and other terminals.
